NMS_MOD_DEFINITION_CONTAINER = 
{
  ["MOD_BATCHNAME"] 			= "zzCodenameAwesome-Assets.pak",
  ["MOD_FILENAME"] 			= "zzCodenameAwesome-Assets-SnowyRadio.pak",
  ["MOD_DESCRIPTION"]		= "Copies the radioactive models and swaps the materials for frozen ones.",
  ["MOD_AUTHOR"]				= "",
  ["NMS_VERSION"]				= "3.13",
  ["MODIFICATIONS"] 		=
	{
		{
			["MBIN_CHANGE_TABLE"] =  {
				{--For testing, add the new models and force them to spawn
					["MBIN_FILE_SOURCE"] = {
						{"METADATA/SIMULATION/SOLARSYSTEM/BIOMES/RADIOACTIVE/RADIOACTIVEOBJECTSFULL.MBIN","METADATA/SIMULATION/SOLARSYSTEM/BIOMES/FROZEN/FROZENHQOBJECTSMID.MBIN"},
						{"METADATA/SIMULATION/SOLARSYSTEM/BIOMES/RADIOACTIVE/RADIOACTIVEOBJECTSFULL.MBIN","METADATA/SIMULATION/SOLARSYSTEM/BIOMES/FROZEN/FROZENHQOBJECTSMIDULTRA.MBIN"},
					},
				},
				{--Testing
					["MBIN_FILE_SOURCE"] = {"METADATA/SIMULATION/SOLARSYSTEM/BIOMES/BIOMEFILENAMES.MBIN"},
					["EXML_CHANGE_TABLE"] = {
						{
							["PRECEDING_KEY_WORDS"] = {"BiomeFiles"},
							["REPLACE_TYPE"] = "ALL",
							["VALUE_CHANGE_TABLE"] = {
								{"FileName","METADATA/SIMULATION/SOLARSYSTEM/BIOMES/FROZEN/FROZENHQBIOME.MXML"}
							},
						}
					}
				},
				{--Testing
					["MBIN_FILE_SOURCE"] = {
						"METADATA/SIMULATION/SOLARSYSTEM/BIOMES/FROZEN/FROZENHQOBJECTSMID.MBIN",
						"METADATA/SIMULATION/SOLARSYSTEM/BIOMES/FROZEN/FROZENHQOBJECTSMIDULTRA.MBIN"
					},
					["EXML_CHANGE_TABLE"] = {
						{
							["REPLACE_TYPE"] = "RAW",
							["VALUE_CHANGE_TABLE"] = {
								{[[MODELS/PLANETS/BIOMES/RADIOACTIVE/]],[[CUSTOMMODELS/BIOMES/SNOWYRADIOACTIVE/]]}
							},
						}
					}
				},
				{--Create the model
					["MBIN_FILE_SOURCE"] = {
						{"MODELS/PLANETS/BIOMES/RADIOACTIVE/LARGE/CURVEDROCK.DESCRIPTOR.MBIN","CUSTOMMODELS/BIOMES/SNOWYRADIOACTIVE/LARGE/CURVEDROCK.DESCRIPTOR.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/RADIOACTIVE/LARGE/CURVEDROCK.SCENE.MBIN","CUSTOMMODELS/BIOMES/SNOWYRADIOACTIVE/LARGE/CURVEDROCK.SCENE.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/RADIOACTIVE/LARGE/LARGEGLOWPLANT.DESCRIPTOR.MBIN","CUSTOMMODELS/BIOMES/SNOWYRADIOACTIVE/LARGE/LARGEGLOWPLANT.DESCRIPTOR.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/RADIOACTIVE/LARGE/LARGEGLOWPLANT.SCENE.MBIN","CUSTOMMODELS/BIOMES/SNOWYRADIOACTIVE/LARGE/LARGEGLOWPLANT.SCENE.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/RADIOACTIVE/LARGE/LARGEGLOWPLANTSINGLE.DESCRIPTOR.MBIN","CUSTOMMODELS/BIOMES/SNOWYRADIOACTIVE/LARGE/LARGEGLOWPLANTSINGLE.DESCRIPTOR.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/RADIOACTIVE/LARGE/LARGEGLOWPLANTSINGLE.SCENE.MBIN","CUSTOMMODELS/BIOMES/SNOWYRADIOACTIVE/LARGE/LARGEGLOWPLANTSINGLE.SCENE.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/RADIOACTIVE/LARGE/RADIOACTIVETREE.DESCRIPTOR.MBIN","CUSTOMMODELS/BIOMES/SNOWYRADIOACTIVE/LARGE/RADIOACTIVETREE.DESCRIPTOR.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/RADIOACTIVE/LARGE/RADIOACTIVETREE.SCENE.MBIN","CUSTOMMODELS/BIOMES/SNOWYRADIOACTIVE/LARGE/RADIOACTIVETREE.SCENE.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/RADIOACTIVE/MEDIUM/CURVEDMEDIUM.DESCRIPTOR.MBIN","CUSTOMMODELS/BIOMES/SNOWYRADIOACTIVE/MEDIUM/CURVEDMEDIUM.DESCRIPTOR.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/RADIOACTIVE/MEDIUM/CURVEDMEDIUM.SCENE.MBIN","CUSTOMMODELS/BIOMES/SNOWYRADIOACTIVE/MEDIUM/CURVEDMEDIUM.SCENE.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/RADIOACTIVE/MEDIUM/MEDIUMGLOWPLANT.DESCRIPTOR.MBIN","CUSTOMMODELS/BIOMES/SNOWYRADIOACTIVE/MEDIUM/MEDIUMGLOWPLANT.DESCRIPTOR.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/RADIOACTIVE/MEDIUM/MEDIUMGLOWPLANT.SCENE.MBIN","CUSTOMMODELS/BIOMES/SNOWYRADIOACTIVE/MEDIUM/MEDIUMGLOWPLANT.SCENE.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/RADIOACTIVE/MEDIUM/MEDIUMGLOWROCK.DESCRIPTOR.MBIN","CUSTOMMODELS/BIOMES/SNOWYRADIOACTIVE/MEDIUM/MEDIUMGLOWROCK.DESCRIPTOR.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/RADIOACTIVE/MEDIUM/MEDIUMGLOWROCK.SCENE.MBIN","CUSTOMMODELS/BIOMES/SNOWYRADIOACTIVE/MEDIUM/MEDIUMGLOWROCK.SCENE.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/RADIOACTIVE/MEDIUM/MEDIUMGLOWROCKSINGLE.DESCRIPTOR.MBIN","CUSTOMMODELS/BIOMES/SNOWYRADIOACTIVE/MEDIUM/MEDIUMGLOWROCKSINGLE.DESCRIPTOR.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/RADIOACTIVE/MEDIUM/MEDIUMGLOWROCKSINGLE.SCENE.MBIN","CUSTOMMODELS/BIOMES/SNOWYRADIOACTIVE/MEDIUM/MEDIUMGLOWROCKSINGLE.SCENE.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/RADIOACTIVE/MEDIUM/MEDIUMSTEAMER.DESCRIPTOR.MBIN","CUSTOMMODELS/BIOMES/SNOWYRADIOACTIVE/MEDIUM/MEDIUMSTEAMER.DESCRIPTOR.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/RADIOACTIVE/MEDIUM/MEDIUMSTEAMER.SCENE.MBIN","CUSTOMMODELS/BIOMES/SNOWYRADIOACTIVE/MEDIUM/MEDIUMSTEAMER.SCENE.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/RADIOACTIVE/SMALL/CURVEDSMALL.DESCRIPTOR.MBIN","CUSTOMMODELS/BIOMES/SNOWYRADIOACTIVE/SMALL/CURVEDSMALL.DESCRIPTOR.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/RADIOACTIVE/SMALL/CURVEDSMALL.SCENE.MBIN","CUSTOMMODELS/BIOMES/SNOWYRADIOACTIVE/SMALL/CURVEDSMALL.SCENE.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/RADIOACTIVE/SMALL/CURVEFRAGMENT.DESCRIPTOR.MBIN","CUSTOMMODELS/BIOMES/SNOWYRADIOACTIVE/SMALL/CURVEFRAGMENT.DESCRIPTOR.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/RADIOACTIVE/SMALL/CURVEFRAGMENT.SCENE.MBIN","CUSTOMMODELS/BIOMES/SNOWYRADIOACTIVE/SMALL/CURVEFRAGMENT.SCENE.MBIN","REMOVE"},
					}
				},
				{
					["MBIN_FILE_SOURCE"] = {"CUSTOMMODELS/BIOMES/SNOWYRADIOACTIVE/LARGE/CURVEDROCK.SCENE.MBIN"},
					["EXML_CHANGE_TABLE"] = {
						{
							["SPECIAL_KEY_WORDS"] = {"Name","MATERIAL"},
							["REPLACE_TYPE"] = "RAW",
							["VALUE_CHANGE_TABLE"] = {
								{[[MODELS\PLANETS\BIOMES\RADIOACTIVE\LARGE\CURVEDROCK\CURVEDROCKMAT.MATERIAL.MBIN]],[[MODELS\PLANETS\BIOMES\FROZEN\MEDIUMPROPS\MEDIUMROCK\TILINGROCKFROZEN_MAT.MATERIAL.MBIN]]},
								--{[[MODELS\PLANETS\BIOMES\RADIOACTIVE\LARGE\CURVEDROCK\GROWTHMAT.MATERIAL.MBIN]],[[]]},
							},
						}
					}
				},
				{
					["MBIN_FILE_SOURCE"] = {"CUSTOMMODELS/BIOMES/SNOWYRADIOACTIVE/LARGE/RADIOACTIVETREE.SCENE.MBIN"},
					["EXML_CHANGE_TABLE"] = {
						{
							["SPECIAL_KEY_WORDS"] = {"Name","MATERIAL"},
							["REPLACE_TYPE"] = "RAW",
							["VALUE_CHANGE_TABLE"] = {
								--{[[MODELS\PLANETS\BIOMES\RADIOACTIVE\LARGE\RADIOACTIVETREE\GROWTHMAT.MATERIAL.MBIN]],[[]]},
								--{[[MODELS\PLANETS\BIOMES\RADIOACTIVE\LARGE\RADIOACTIVETREE\IMPOST_IMPOSTERMAT.MATERIAL.MBIN]],[[]]},
								{[[MODELS\PLANETS\BIOMES\RADIOACTIVE\LARGE\RADIOACTIVETREE\RADIATIONBARKMAT.MATERIAL.MBIN]],[[MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\BARK.MATERIAL.MBIN]]},
								{[[MODELS\PLANETS\BIOMES\RADIOACTIVE\LARGE\RADIOACTIVETREE\RADLEAFMAT.MATERIAL.MBIN]],[[MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\FROZENFRONDMAT.MATERIAL.MBIN]]},
								--{[[MODELS\PLANETS\BIOMES\RADIOACTIVE\LARGE\RADIOACTIVETREE\VINETEST.MATERIAL.MBIN]],[[]]},
							},
						}
					}
				},
				{
					["MBIN_FILE_SOURCE"] = {"CUSTOMMODELS/BIOMES/SNOWYRADIOACTIVE/MEDIUM/CURVEDMEDIUM.SCENE.MBIN"},
					["EXML_CHANGE_TABLE"] = {
						{
							["SPECIAL_KEY_WORDS"] = {"Name","MATERIAL"},
							["REPLACE_TYPE"] = "RAW",
							["VALUE_CHANGE_TABLE"] = {
								{[[MODELS\PLANETS\BIOMES\RADIOACTIVE\MEDIUM\CURVEDMEDIUM\CURVEROCK_CURVEDROCKMAT.MATERIAL.MBIN]],[[MODELS\PLANETS\BIOMES\FROZEN\MEDIUMPROPS\MEDIUMROCK\TILINGROCKFROZEN_MAT.MATERIAL.MBIN]]},
							},
						}
					}
				},
				{
					["MBIN_FILE_SOURCE"] = {"CUSTOMMODELS/BIOMES/SNOWYRADIOACTIVE/MEDIUM/MEDIUMSTEAMER.SCENE.MBIN"},
					["EXML_CHANGE_TABLE"] = {
						{
							["SPECIAL_KEY_WORDS"] = {"Name","MATERIAL"},
							["REPLACE_TYPE"] = "RAW",
							["VALUE_CHANGE_TABLE"] = {
								--{[[MODELS\PLANETS\BIOMES\RADIOACTIVE\MEDIUM\MEDIUMSTEAMER\HAZARDSTEAM_POISONMAT.MATERIAL.MBIN]],[[]]},
								--{[[MODELS\PLANETS\BIOMES\RADIOACTIVE\MEDIUM\MEDIUMSTEAMER\SMOKE_RED_CLOUDPARTICLE.MATERIAL.MBIN]],[[]]},
								{[[MODELS\PLANETS\BIOMES\RADIOACTIVE\MEDIUM\MEDIUMSTEAMER\CURVEDROCKMAT.MATERIAL.MBIN]],[[MODELS\PLANETS\BIOMES\FROZEN\MEDIUMPROPS\MEDIUMROCK\TILINGROCKFROZEN_MAT.MATERIAL.MBIN]]},
							},
						}
					}
				},
				{
					["MBIN_FILE_SOURCE"] = {"CUSTOMMODELS/BIOMES/SNOWYRADIOACTIVE/SMALL/CURVEDSMALL.SCENE.MBIN"},
					["EXML_CHANGE_TABLE"] = {
						{
							["SPECIAL_KEY_WORDS"] = {"Name","MATERIAL"},
							["REPLACE_TYPE"] = "RAW",
							["VALUE_CHANGE_TABLE"] = {
								{[[MODELS\PLANETS\BIOMES\RADIOACTIVE\SMALL\CURVEDSMALL\CURVEDROCKMAT.MATERIAL.MBIN]],[[MODELS\PLANETS\BIOMES\FROZEN\MEDIUMPROPS\MEDIUMROCK\TILINGROCKFROZEN_MAT.MATERIAL.MBIN]]}
							},
						}
					}
				},
				{
					["MBIN_FILE_SOURCE"] = {"CUSTOMMODELS/BIOMES/SNOWYRADIOACTIVE/SMALL/CURVEFRAGMENT.SCENE.MBIN"},
					["EXML_CHANGE_TABLE"] = {
						{
							["SPECIAL_KEY_WORDS"] = {"Name","MATERIAL"},
							["REPLACE_TYPE"] = "RAW",
							["VALUE_CHANGE_TABLE"] = {
								{[[MODELS\PLANETS\BIOMES\RADIOACTIVE\SMALL\CURVEFRAGMENT\CURVEDROCKMAT.MATERIAL.MBIN]],[[MODELS\PLANETS\BIOMES\FROZEN\MEDIUMPROPS\MEDIUMROCK\TILINGROCKFROZEN_MAT.MATERIAL.MBIN]],}
							},
						}
					}
				},
			}
		},
	}
}
--NOTE: ANYTHING NOT in table NMS_MOD_DEFINITION_CONTAINER IS IGNORED AFTER THE SCRIPT IS LOADED
--IT IS BETTER TO ADD THINGS AT THE TOP IF YOU NEED TO
--DON'T ADD ANYTHING PASS THIS POINT HERE