NMS_MOD_DEFINITION_CONTAINER = 
{
  ["MOD_BATCHNAME"] 			= "zzCodenameAwesome-Assets.pak",
  ["MOD_FILENAME"] 			= "zzCodenameAwesome-Assets-SnowyHQTREEREF.pak",
  ["MOD_DESCRIPTION"]		= "Copies the HQTREES model and swaps the materials for ones from the Frozen trees.",
  ["MOD_AUTHOR"]				= "",
  ["NMS_VERSION"]				= "3.13",
  ["MODIFICATIONS"] 		=
	{
		{
			["MBIN_CHANGE_TABLE"] =  {
				{--Create the model
					["MBIN_FILE_SOURCE"] = {
						{"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/HQTREEREF.DESCRIPTOR.MBIN","CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/HQTREEREF.DESCRIPTOR.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/HQTREEREF.SCENE.MBIN","CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/HQTREEREF.SCENE.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE01.DESCRIPTOR.MBIN","CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE01.DESCRIPTOR.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE01.SCENE.MBIN","CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE01.SCENE.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE02.DESCRIPTOR.MBIN","CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE02.DESCRIPTOR.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE02.SCENE.MBIN","CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE02.SCENE.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE03.DESCRIPTOR.MBIN","CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE03.DESCRIPTOR.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE03.SCENE.MBIN","CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE03.SCENE.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE04.DESCRIPTOR.MBIN","CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE04.DESCRIPTOR.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE04.SCENE.MBIN","CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE04.SCENE.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE05.DESCRIPTOR.MBIN","CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE05.DESCRIPTOR.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE05.SCENE.MBIN","CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE05.SCENE.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE06.DESCRIPTOR.MBIN","CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE06.DESCRIPTOR.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE06.SCENE.MBIN","CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE06.SCENE.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE07.DESCRIPTOR.MBIN","CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE07.DESCRIPTOR.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE07.SCENE.MBIN","CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE07.SCENE.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE08.DESCRIPTOR.MBIN","CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE08.DESCRIPTOR.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE08.SCENE.MBIN","CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE08.SCENE.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE09.DESCRIPTOR.MBIN","CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE09.DESCRIPTOR.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE09.SCENE.MBIN","CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE09.SCENE.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE10.DESCRIPTOR.MBIN","CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE10.DESCRIPTOR.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE10.SCENE.MBIN","CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE10.SCENE.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE11.DESCRIPTOR.MBIN","CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE11.DESCRIPTOR.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE11.SCENE.MBIN","CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE11.SCENE.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE12.DESCRIPTOR.MBIN","CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE12.DESCRIPTOR.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE12.SCENE.MBIN","CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE12.SCENE.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE13.DESCRIPTOR.MBIN","CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE13.DESCRIPTOR.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE13.SCENE.MBIN","CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE13.SCENE.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE14.DESCRIPTOR.MBIN","CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE14.DESCRIPTOR.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE14.SCENE.MBIN","CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE14.SCENE.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE15.DESCRIPTOR.MBIN","CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE15.DESCRIPTOR.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE15.SCENE.MBIN","CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE15.SCENE.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE16.DESCRIPTOR.MBIN","CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE16.DESCRIPTOR.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE16.SCENE.MBIN","CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE16.SCENE.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE17.DESCRIPTOR.MBIN","CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE17.DESCRIPTOR.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE17.SCENE.MBIN","CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE17.SCENE.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE18.DESCRIPTOR.MBIN","CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE18.DESCRIPTOR.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE18.SCENE.MBIN","CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE18.SCENE.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE19.DESCRIPTOR.MBIN","CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE19.DESCRIPTOR.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE19.SCENE.MBIN","CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE19.SCENE.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE20.DESCRIPTOR.MBIN","CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE20.DESCRIPTOR.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE20.SCENE.MBIN","CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE20.SCENE.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE21.DESCRIPTOR.MBIN","CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE21.DESCRIPTOR.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE21.SCENE.MBIN","CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE21.SCENE.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE22.DESCRIPTOR.MBIN","CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE22.DESCRIPTOR.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE22.SCENE.MBIN","CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE22.SCENE.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE23.DESCRIPTOR.MBIN","CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE23.DESCRIPTOR.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE23.SCENE.MBIN","CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE23.SCENE.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE24.DESCRIPTOR.MBIN","CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE24.DESCRIPTOR.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE24.SCENE.MBIN","CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE24.SCENE.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE25.DESCRIPTOR.MBIN","CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE25.DESCRIPTOR.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE25.SCENE.MBIN","CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE25.SCENE.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE26.DESCRIPTOR.MBIN","CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE26.DESCRIPTOR.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE26.SCENE.MBIN","CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE26.SCENE.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE27.DESCRIPTOR.MBIN","CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE27.DESCRIPTOR.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE27.SCENE.MBIN","CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE27.SCENE.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE28.DESCRIPTOR.MBIN","CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE28.DESCRIPTOR.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE28.SCENE.MBIN","CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE28.SCENE.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE29.DESCRIPTOR.MBIN","CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE29.DESCRIPTOR.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE29.SCENE.MBIN","CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE29.SCENE.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE30.DESCRIPTOR.MBIN","CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE30.DESCRIPTOR.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE30.SCENE.MBIN","CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE30.SCENE.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE31.DESCRIPTOR.MBIN","CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE31.DESCRIPTOR.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE31.SCENE.MBIN","CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE31.SCENE.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE32.DESCRIPTOR.MBIN","CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE32.DESCRIPTOR.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE32.SCENE.MBIN","CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE32.SCENE.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE33.DESCRIPTOR.MBIN","CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE33.DESCRIPTOR.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE33.SCENE.MBIN","CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE33.SCENE.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE34.DESCRIPTOR.MBIN","CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE34.DESCRIPTOR.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE34.SCENE.MBIN","CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE34.SCENE.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE35.DESCRIPTOR.MBIN","CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE35.DESCRIPTOR.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE35.SCENE.MBIN","CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE35.SCENE.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE36.DESCRIPTOR.MBIN","CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE36.DESCRIPTOR.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE36.SCENE.MBIN","CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE36.SCENE.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE37.DESCRIPTOR.MBIN","CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE37.DESCRIPTOR.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE37.SCENE.MBIN","CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE37.SCENE.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE38.DESCRIPTOR.MBIN","CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE38.DESCRIPTOR.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE38.SCENE.MBIN","CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE38.SCENE.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE39.DESCRIPTOR.MBIN","CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE39.DESCRIPTOR.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE39.SCENE.MBIN","CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE39.SCENE.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE40.DESCRIPTOR.MBIN","CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE40.DESCRIPTOR.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE40.SCENE.MBIN","CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE40.SCENE.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE41.DESCRIPTOR.MBIN","CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE41.DESCRIPTOR.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE41.SCENE.MBIN","CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE41.SCENE.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE42.DESCRIPTOR.MBIN","CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE42.DESCRIPTOR.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE42.SCENE.MBIN","CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE42.SCENE.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE43.DESCRIPTOR.MBIN","CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE43.DESCRIPTOR.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE43.SCENE.MBIN","CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE43.SCENE.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE44.DESCRIPTOR.MBIN","CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE44.DESCRIPTOR.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE44.SCENE.MBIN","CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE44.SCENE.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE45.DESCRIPTOR.MBIN","CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE45.DESCRIPTOR.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE45.SCENE.MBIN","CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE45.SCENE.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE46.DESCRIPTOR.MBIN","CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE46.DESCRIPTOR.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE46.SCENE.MBIN","CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE46.SCENE.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE47.DESCRIPTOR.MBIN","CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE47.DESCRIPTOR.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE47.SCENE.MBIN","CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE47.SCENE.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE48.DESCRIPTOR.MBIN","CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE48.DESCRIPTOR.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE48.SCENE.MBIN","CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE48.SCENE.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE49.DESCRIPTOR.MBIN","CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE49.DESCRIPTOR.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE49.SCENE.MBIN","CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE49.SCENE.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE50.DESCRIPTOR.MBIN","CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE50.DESCRIPTOR.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE50.SCENE.MBIN","CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE50.SCENE.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE51.DESCRIPTOR.MBIN","CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE51.DESCRIPTOR.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE51.SCENE.MBIN","CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE51.SCENE.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE52.DESCRIPTOR.MBIN","CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE52.DESCRIPTOR.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE52.SCENE.MBIN","CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE52.SCENE.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE53.DESCRIPTOR.MBIN","CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE53.DESCRIPTOR.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE53.SCENE.MBIN","CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE53.SCENE.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE54.DESCRIPTOR.MBIN","CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE54.DESCRIPTOR.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE54.SCENE.MBIN","CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE54.SCENE.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE55.DESCRIPTOR.MBIN","CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE55.DESCRIPTOR.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE55.SCENE.MBIN","CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE55.SCENE.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE56.DESCRIPTOR.MBIN","CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE56.DESCRIPTOR.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE56.SCENE.MBIN","CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE56.SCENE.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE57.DESCRIPTOR.MBIN","CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE57.DESCRIPTOR.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE57.SCENE.MBIN","CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE57.SCENE.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE58.DESCRIPTOR.MBIN","CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE58.DESCRIPTOR.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE58.SCENE.MBIN","CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE58.SCENE.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE59.DESCRIPTOR.MBIN","CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE59.DESCRIPTOR.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE59.SCENE.MBIN","CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE59.SCENE.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE60.DESCRIPTOR.MBIN","CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE60.DESCRIPTOR.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE60.SCENE.MBIN","CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE60.SCENE.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE61.DESCRIPTOR.MBIN","CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE61.DESCRIPTOR.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE61.SCENE.MBIN","CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE61.SCENE.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE62.DESCRIPTOR.MBIN","CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE62.DESCRIPTOR.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE62.SCENE.MBIN","CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE62.SCENE.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE63.DESCRIPTOR.MBIN","CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE63.DESCRIPTOR.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE63.SCENE.MBIN","CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE63.SCENE.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE64.DESCRIPTOR.MBIN","CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE64.DESCRIPTOR.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE64.SCENE.MBIN","CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE64.SCENE.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE65.DESCRIPTOR.MBIN","CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE65.DESCRIPTOR.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE65.SCENE.MBIN","CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE65.SCENE.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE66.DESCRIPTOR.MBIN","CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE66.DESCRIPTOR.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE66.SCENE.MBIN","CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE66.SCENE.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE67.DESCRIPTOR.MBIN","CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE67.DESCRIPTOR.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE67.SCENE.MBIN","CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE67.SCENE.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE68.DESCRIPTOR.MBIN","CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE68.DESCRIPTOR.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE68.SCENE.MBIN","CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE68.SCENE.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE69.DESCRIPTOR.MBIN","CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE69.DESCRIPTOR.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE69.SCENE.MBIN","CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE69.SCENE.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE70.DESCRIPTOR.MBIN","CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE70.DESCRIPTOR.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE70.SCENE.MBIN","CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE70.SCENE.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE71.DESCRIPTOR.MBIN","CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE71.DESCRIPTOR.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE71.SCENE.MBIN","CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE71.SCENE.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE72.DESCRIPTOR.MBIN","CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE72.DESCRIPTOR.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE72.SCENE.MBIN","CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE72.SCENE.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE73.DESCRIPTOR.MBIN","CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE73.DESCRIPTOR.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE73.SCENE.MBIN","CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE73.SCENE.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE74.DESCRIPTOR.MBIN","CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE74.DESCRIPTOR.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE74.SCENE.MBIN","CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE74.SCENE.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE75.DESCRIPTOR.MBIN","CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE75.DESCRIPTOR.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE75.SCENE.MBIN","CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE75.SCENE.MBIN","REMOVE"},
					}
				},
				{--Reference the new PARTS in the main REF scene
					["MBIN_FILE_SOURCE"] = {"CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/HQTREEREF.SCENE.MBIN"},
					["EXML_CHANGE_TABLE"] = {
						{
							["SPECIAL_KEY_WORDS"] = {"Name","SCENEGRAPH"},
							["REPLACE_TYPE"] = "RAW",
							["VALUE_CHANGE_TABLE"] = {
								{[[MODELS\PLANETS\BIOMES\HQLUSH\HQTREES\PARTS\]],[[CUSTOMMODELS\CODENAMEAWESOME\BIOMES\SNOWYHQLUSH\HQTREES\PARTS\]]}
							}
						}
					}
				},
				{--Create new non-billboard version of BILLBOADLEAVES_NEWLEAFMAT
					["MBIN_FILE_SOURCE"] = {
						{"MODELS/PLANETS/BIOMES/HQLUSH/HQTREES/PARTS/HQTREE11/LEAF.MATERIAL.MBIN","CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/NONBILLBOADLEAVES_NEWLEAFMAT.MATERIAL.MBIN","REMOVE"},
					}
				},
				{--Replace the textures in NONBILLBOADLEAVES_NEWLEAFMAT
					["MBIN_FILE_SOURCE"] = {"CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/NONBILLBOADLEAVES_NEWLEAFMAT.MATERIAL.MBIN"},
					["EXML_CHANGE_TABLE"] = {
						{
							["PRECEDING_KEY_WORDS"] = {"Samplers"},
							["REPLACE_TYPE"] = "RAW",
							["VALUE_CHANGE_TABLE"]  = {
								{[[TEXTURES/PLANETS/BIOMES/COMMON/LEAVES/HQLEAVES/HQCROSSLEAF.BASE.]],[[TEXTURES/PLANETS/BIOMES/FROZEN/LARGEPROPS/SNOWBILLLEAF.BASE.]]}
							}
						}
					}
				},
				{--Swap HQTREE01 materials
					["MBIN_FILE_SOURCE"] = {"CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE01.SCENE.MBIN",},
					["EXML_CHANGE_TABLE"] = {
						{
							["SPECIAL_KEY_WORDS"] = {"Name","MATERIAL"},
							["REPLACE_TYPE"] = "RAW",
							["VALUE_CHANGE_TABLE"] = {
								{[[MODELS\PLANETS\BIOMES\HQLUSH\HQTREES\PARTS\HQTREE01\BARK1.MATERIAL.MBIN]],[[MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\BARK.MATERIAL.MBIN]]},
								{[[MODELS\PLANETS\BIOMES\HQLUSH\HQTREES\PARTS\HQTREE01\HQFROND1.MATERIAL.MBIN]],[[MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\FROZENFRONDMAT.MATERIAL.MBIN]]},
							}
						}
					}
				},
				{--Swap HQTREE02 materials
					["MBIN_FILE_SOURCE"] = {"CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE02.SCENE.MBIN",},
					["EXML_CHANGE_TABLE"] = {
						{
							["SPECIAL_KEY_WORDS"] = {"Name","MATERIAL"},
							["REPLACE_TYPE"] = "RAW",
							["VALUE_CHANGE_TABLE"] = {
								{[[MODELS\PLANETS\BIOMES\HQLUSH\HQTREES\PARTS\HQTREE02\BARK1.MATERIAL.MBIN]],[[MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\BARK.MATERIAL.MBIN]]},
								{[[MODELS\PLANETS\BIOMES\HQLUSH\HQTREES\PARTS\HQTREE02\HQFROND2.MATERIAL.MBIN]],[[MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\FROZENFRONDMAT.MATERIAL.MBIN]]},
							}
						}
					}
				},
				{--Swap HQTREE03 materials
					["MBIN_FILE_SOURCE"] = {"CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE03.SCENE.MBIN",},
					["EXML_CHANGE_TABLE"] = {
						{
							["SPECIAL_KEY_WORDS"] = {"Name","MATERIAL"},
							["REPLACE_TYPE"] = "RAW",
							["VALUE_CHANGE_TABLE"] = {
								{[[MODELS\PLANETS\BIOMES\HQLUSH\HQTREES\PARTS\HQTREE03\BARK1.MATERIAL.MBIN]],[[MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\BARK.MATERIAL.MBIN]]},
								{[[MODELS\PLANETS\BIOMES\HQLUSH\HQTREES\PARTS\HQTREE03\HQFROND3.MATERIAL.MBIN]],[[MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\FROZENFRONDMAT.MATERIAL.MBIN]]},
							}
						}
					}
				},
				{--Swap HQTREE04 materials
					["MBIN_FILE_SOURCE"] = {"CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE04.SCENE.MBIN",},
					["EXML_CHANGE_TABLE"] = {
						{
							["SPECIAL_KEY_WORDS"] = {"Name","MATERIAL"},
							["REPLACE_TYPE"] = "RAW",
							["VALUE_CHANGE_TABLE"] = {
								{[[MODELS\PLANETS\BIOMES\HQLUSH\HQTREES\PARTS\HQTREE04\BARK1.MATERIAL.MBIN]],[[MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\BARK.MATERIAL.MBIN]]},
								{[[MODELS\PLANETS\BIOMES\HQLUSH\HQTREES\PARTS\HQTREE04\HQFROND4.MATERIAL.MBIN]],[[MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\FROZENFRONDMAT.MATERIAL.MBIN]]},
							}
						}
					}
				},
				{--Swap HQTREE05 materials
					["MBIN_FILE_SOURCE"] = {"CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE05.SCENE.MBIN",},
					["EXML_CHANGE_TABLE"] = {
						{
							["SPECIAL_KEY_WORDS"] = {"Name","MATERIAL"},
							["REPLACE_TYPE"] = "RAW",
							["VALUE_CHANGE_TABLE"] = {
								{[[MODELS\PLANETS\BIOMES\HQLUSH\HQTREES\PARTS\HQTREE05\BARK1.MATERIAL.MBIN]],[[MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\BARK.MATERIAL.MBIN]]},
								{[[MODELS\PLANETS\BIOMES\HQLUSH\HQTREES\PARTS\HQTREE05\HQFROND5.MATERIAL.MBIN]],[[MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\FROZENFRONDMAT.MATERIAL.MBIN]]},
							}
						}
					}
				},
				{--Swap HQTREE06 materials
					["MBIN_FILE_SOURCE"] = {"CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE06.SCENE.MBIN",},
					["EXML_CHANGE_TABLE"] = {
						{
							["SPECIAL_KEY_WORDS"] = {"Name","MATERIAL"},
							["REPLACE_TYPE"] = "RAW",
							["VALUE_CHANGE_TABLE"] = {
								{[[MODELS\PLANETS\BIOMES\HQLUSH\HQTREES\PARTS\HQTREE06\BARK1.MATERIAL.MBIN]],[[MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\BARK.MATERIAL.MBIN]]},
								{[[MODELS\PLANETS\BIOMES\HQLUSH\HQTREES\PARTS\HQTREE06\HQFROND6.MATERIAL.MBIN]],[[MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\FROZENFRONDMAT.MATERIAL.MBIN]]},
							}
						}
					}
				},
				{--Swap HQTREE07 materials
					["MBIN_FILE_SOURCE"] = {"CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE07.SCENE.MBIN",},
					["EXML_CHANGE_TABLE"] = {
						{
							["SPECIAL_KEY_WORDS"] = {"Name","MATERIAL"},
							["REPLACE_TYPE"] = "RAW",
							["VALUE_CHANGE_TABLE"] = {
								{[[MODELS\PLANETS\BIOMES\HQLUSH\HQTREES\PARTS\HQTREE07\BARK1.MATERIAL.MBIN]],[[MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\BARK.MATERIAL.MBIN]]},
								{[[MODELS\PLANETS\BIOMES\HQLUSH\HQTREES\PARTS\HQTREE07\HQFROND7.MATERIAL.MBIN]],[[MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\FROZENFRONDMAT.MATERIAL.MBIN]]},
							}
						}
					}
				},
				{--Swap HQTREE08 materials
					["MBIN_FILE_SOURCE"] = {"CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE08.SCENE.MBIN",},
					["EXML_CHANGE_TABLE"] = {
						{
							["SPECIAL_KEY_WORDS"] = {"Name","MATERIAL"},
							["REPLACE_TYPE"] = "RAW",
							["VALUE_CHANGE_TABLE"] = {
								{[[MODELS\PLANETS\BIOMES\HQLUSH\HQTREES\PARTS\HQTREE08\BARK1.MATERIAL.MBIN]],[[MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\BARK.MATERIAL.MBIN]]},
								{[[MODELS\PLANETS\BIOMES\HQLUSH\HQTREES\PARTS\HQTREE08\HQFROND8.MATERIAL.MBIN]],[[MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\FROZENFRONDMAT.MATERIAL.MBIN]]},
							}
						}
					}
				},
				{--Swap HQTREE09 materials
					["MBIN_FILE_SOURCE"] = {"CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE09.SCENE.MBIN",},
					["EXML_CHANGE_TABLE"] = {
						{
							["SPECIAL_KEY_WORDS"] = {"Name","MATERIAL"},
							["REPLACE_TYPE"] = "RAW",
							["VALUE_CHANGE_TABLE"] = {
								{[[MODELS\PLANETS\BIOMES\HQLUSH\HQTREES\PARTS\HQTREE09\BARK1.MATERIAL.MBIN]],[[MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\BARK.MATERIAL.MBIN]]},
								{[[MODELS\PLANETS\BIOMES\HQLUSH\HQTREES\PARTS\HQTREE09\HQFROND9.MATERIAL.MBIN]],[[MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\FROZENFRONDMAT.MATERIAL.MBIN]]},
							}
						}
					}
				},
				{--Swap HQTREE10 materials
					["MBIN_FILE_SOURCE"] = {"CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE10.SCENE.MBIN",},
					["EXML_CHANGE_TABLE"] = {
						{
							["SPECIAL_KEY_WORDS"] = {"Name","MATERIAL"},
							["REPLACE_TYPE"] = "RAW",
							["VALUE_CHANGE_TABLE"] = {
								{[[MODELS\PLANETS\BIOMES\HQLUSH\HQTREES\PARTS\HQTREE10\BARK1.MATERIAL.MBIN]],[[MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\BARK.MATERIAL.MBIN]]},
								{[[MODELS\PLANETS\BIOMES\HQLUSH\HQTREES\PARTS\HQTREE10\HQFROND10.MATERIAL.MBIN]],[[MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\FROZENFRONDMAT.MATERIAL.MBIN]]},
							}
						}
					}
				},
				{--Swap HQTREE11 materials
					["MBIN_FILE_SOURCE"] = {"CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE11.SCENE.MBIN",},
					["EXML_CHANGE_TABLE"] = {
						{
							["SPECIAL_KEY_WORDS"] = {"Name","MATERIAL"},
							["REPLACE_TYPE"] = "RAW",
							["VALUE_CHANGE_TABLE"] = {
								{[[MODELS\PLANETS\BIOMES\HQLUSH\HQTREES\PARTS\HQTREE11\BARK1.MATERIAL.MBIN]],[[MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\BARK.MATERIAL.MBIN]]},
								{[[MODELS\PLANETS\BIOMES\HQLUSH\HQTREES\PARTS\HQTREE11\LEAF.MATERIAL.MBIN]],[[CUSTOMMODELS\CODENAMEAWESOME\BIOMES\SNOWYHQLUSH\NONBILLBOADLEAVES_NEWLEAFMAT.MATERIAL.MBIN]]},
							}
						}
					}
				},
				{--Swap HQTREE12 materials
					["MBIN_FILE_SOURCE"] = {"CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE12.SCENE.MBIN",},
					["EXML_CHANGE_TABLE"] = {
						{
							["SPECIAL_KEY_WORDS"] = {"Name","MATERIAL"},
							["REPLACE_TYPE"] = "RAW",
							["VALUE_CHANGE_TABLE"] = {
								{[[MODELS\PLANETS\BIOMES\HQLUSH\HQTREES\PARTS\HQTREE12\BARK1.MATERIAL.MBIN]],[[MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\BARK.MATERIAL.MBIN]]},
								{[[MODELS\PLANETS\BIOMES\HQLUSH\HQTREES\PARTS\HQTREE12\HQFROND1.MATERIAL.MBIN]],[[MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\FROZENFRONDMAT.MATERIAL.MBIN]]},
							}
						}
					}
				},
				{--Swap HQTREE13 materials
					["MBIN_FILE_SOURCE"] = {"CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE13.SCENE.MBIN",},
					["EXML_CHANGE_TABLE"] = {
						{
							["SPECIAL_KEY_WORDS"] = {"Name","MATERIAL"},
							["REPLACE_TYPE"] = "RAW",
							["VALUE_CHANGE_TABLE"] = {
								{[[MODELS\PLANETS\BIOMES\HQLUSH\HQTREES\PARTS\HQTREE13\BARK1.MATERIAL.MBIN]],[[MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\BARK.MATERIAL.MBIN]]},
								{[[MODELS\PLANETS\BIOMES\HQLUSH\HQTREES\PARTS\HQTREE13\HQFROND2.MATERIAL.MBIN]],[[MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\FROZENFRONDMAT.MATERIAL.MBIN]]},
							}
						}
					}
				},
				{--Swap HQTREE14 materials
					["MBIN_FILE_SOURCE"] = {"CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE14.SCENE.MBIN",},
					["EXML_CHANGE_TABLE"] = {
						{
							["SPECIAL_KEY_WORDS"] = {"Name","MATERIAL"},
							["REPLACE_TYPE"] = "RAW",
							["VALUE_CHANGE_TABLE"] = {
								{[[MODELS\PLANETS\BIOMES\HQLUSH\HQTREES\PARTS\HQTREE14\BARK1.MATERIAL.MBIN]],[[MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\BARK.MATERIAL.MBIN]]},
								{[[MODELS\PLANETS\BIOMES\HQLUSH\HQTREES\PARTS\HQTREE14\HQFROND6.MATERIAL.MBIN]],[[MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\FROZENFRONDMAT.MATERIAL.MBIN]]},
							}
						}
					}
				},
				{--Swap HQTREE15 materials
					["MBIN_FILE_SOURCE"] = {"CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE15.SCENE.MBIN",},
					["EXML_CHANGE_TABLE"] = {
						{
							["SPECIAL_KEY_WORDS"] = {"Name","MATERIAL"},
							["REPLACE_TYPE"] = "RAW",
							["VALUE_CHANGE_TABLE"] = {
								{[[MODELS\PLANETS\BIOMES\HQLUSH\HQTREES\PARTS\HQTREE15\BARK1.MATERIAL.MBIN]],[[MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\BARK.MATERIAL.MBIN]]},
								{[[MODELS\PLANETS\BIOMES\HQLUSH\HQTREES\PARTS\HQTREE15\HQFROND3.MATERIAL.MBIN]],[[MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\FROZENFRONDMAT.MATERIAL.MBIN]]},
							}
						}
					}
				},
				{--Swap HQTREE16 materials
					["MBIN_FILE_SOURCE"] = {"CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE16.SCENE.MBIN",},
					["EXML_CHANGE_TABLE"] = {
						{
							["SPECIAL_KEY_WORDS"] = {"Name","MATERIAL"},
							["REPLACE_TYPE"] = "RAW",
							["VALUE_CHANGE_TABLE"] = {
								{[[MODELS\PLANETS\BIOMES\HQLUSH\HQTREES\PARTS\HQTREE16\BARK1.MATERIAL.MBIN]],[[MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\BARK.MATERIAL.MBIN]]},
								{[[MODELS\PLANETS\BIOMES\HQLUSH\HQTREES\PARTS\HQTREE16\HQFROND4.MATERIAL.MBIN]],[[MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\FROZENFRONDMAT.MATERIAL.MBIN]]},
							}
						}
					}
				},
				{--Swap HQTREE17 materials
					["MBIN_FILE_SOURCE"] = {"CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE17.SCENE.MBIN",},
					["EXML_CHANGE_TABLE"] = {
						{
							["SPECIAL_KEY_WORDS"] = {"Name","MATERIAL"},
							["REPLACE_TYPE"] = "RAW",
							["VALUE_CHANGE_TABLE"] = {
								{[[MODELS\PLANETS\BIOMES\HQLUSH\HQTREES\PARTS\HQTREE17\BARK1.MATERIAL.MBIN]],[[MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\BARK.MATERIAL.MBIN]]},
								{[[MODELS\PLANETS\BIOMES\HQLUSH\HQTREES\PARTS\HQTREE17\HQFROND10.MATERIAL.MBIN]],[[MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\FROZENFRONDMAT.MATERIAL.MBIN]]},
							}
						}
					}
				},
				{--Swap HQTREE18 materials
					["MBIN_FILE_SOURCE"] = {"CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE18.SCENE.MBIN",},
					["EXML_CHANGE_TABLE"] = {
						{
							["SPECIAL_KEY_WORDS"] = {"Name","MATERIAL"},
							["REPLACE_TYPE"] = "RAW",
							["VALUE_CHANGE_TABLE"] = {
								{[[MODELS\PLANETS\BIOMES\HQLUSH\HQTREES\PARTS\HQTREE18\BARK1.MATERIAL.MBIN]],[[MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\BARK.MATERIAL.MBIN]]},
								{[[MODELS\PLANETS\BIOMES\HQLUSH\HQTREES\PARTS\HQTREE18\HQFROND1.MATERIAL.MBIN]],[[MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\FROZENFRONDMAT.MATERIAL.MBIN]]},
								{[[MODELS\PLANETS\BIOMES\HQLUSH\HQTREES\PARTS\HQTREE18\HQFROND2.MATERIAL.MBIN]],[[MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\FROZENFRONDMAT.MATERIAL.MBIN]]},
							}
						}
					}
				},
				{--Swap HQTREE19 materials
					["MBIN_FILE_SOURCE"] = {"CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE19.SCENE.MBIN",},
					["EXML_CHANGE_TABLE"] = {
						{
							["SPECIAL_KEY_WORDS"] = {"Name","MATERIAL"},
							["REPLACE_TYPE"] = "RAW",
							["VALUE_CHANGE_TABLE"] = {
								{[[MODELS\PLANETS\BIOMES\HQLUSH\HQTREES\PARTS\HQTREE19\BARK1.MATERIAL.MBIN]],[[MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\BARK.MATERIAL.MBIN]]},
								{[[MODELS\PLANETS\BIOMES\HQLUSH\HQTREES\PARTS\HQTREE19\HQFROND1.MATERIAL.MBIN]],[[MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\FROZENFRONDMAT.MATERIAL.MBIN]]},
								{[[MODELS\PLANETS\BIOMES\HQLUSH\HQTREES\PARTS\HQTREE19\HQFROND2.MATERIAL.MBIN]],[[MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\FROZENFRONDMAT.MATERIAL.MBIN]]},
							}
						}
					}
				},
				{--Swap HQTREE20 materials
					["MBIN_FILE_SOURCE"] = {"CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE20.SCENE.MBIN",},
					["EXML_CHANGE_TABLE"] = {
						{
							["SPECIAL_KEY_WORDS"] = {"Name","MATERIAL"},
							["REPLACE_TYPE"] = "RAW",
							["VALUE_CHANGE_TABLE"] = {
								{[[MODELS\PLANETS\BIOMES\HQLUSH\HQTREES\PARTS\HQTREE20\BARK1.MATERIAL.MBIN]],[[MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\BARK.MATERIAL.MBIN]]},
								{[[MODELS\PLANETS\BIOMES\HQLUSH\HQTREES\PARTS\HQTREE20\HQFROND6.MATERIAL.MBIN]],[[MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\FROZENFRONDMAT.MATERIAL.MBIN]]},
							}
						}
					}
				},
				{--Swap HQTREE21 materials
					["MBIN_FILE_SOURCE"] = {"CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE21.SCENE.MBIN",},
					["EXML_CHANGE_TABLE"] = {
						{
							["SPECIAL_KEY_WORDS"] = {"Name","MATERIAL"},
							["REPLACE_TYPE"] = "RAW",
							["VALUE_CHANGE_TABLE"] = {
								{[[MODELS\PLANETS\BIOMES\HQLUSH\HQTREES\PARTS\HQTREE21\BARK1.MATERIAL.MBIN]],[[MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\BARK.MATERIAL.MBIN]]},
								{[[MODELS\PLANETS\BIOMES\HQLUSH\HQTREES\PARTS\HQTREE21\HQFROND7.MATERIAL.MBIN]],[[MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\FROZENFRONDMAT.MATERIAL.MBIN]]},
							}
						}
					}
				},
				{--Swap HQTREE22 materials
					["MBIN_FILE_SOURCE"] = {"CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE22.SCENE.MBIN",},
					["EXML_CHANGE_TABLE"] = {
						{
							["SPECIAL_KEY_WORDS"] = {"Name","MATERIAL"},
							["REPLACE_TYPE"] = "RAW",
							["VALUE_CHANGE_TABLE"] = {
								{[[MODELS\PLANETS\BIOMES\HQLUSH\HQTREES\PARTS\HQTREE22\BARK1.MATERIAL.MBIN]],[[MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\BARK.MATERIAL.MBIN]]},
								{[[MODELS\PLANETS\BIOMES\HQLUSH\HQTREES\PARTS\HQTREE22\HQFROND1.MATERIAL.MBIN]],[[MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\FROZENFRONDMAT.MATERIAL.MBIN]]},
							}
						}
					}
				},
				{--Swap HQTREE23 materials
					["MBIN_FILE_SOURCE"] = {"CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE23.SCENE.MBIN",},
					["EXML_CHANGE_TABLE"] = {
						{
							["SPECIAL_KEY_WORDS"] = {"Name","MATERIAL"},
							["REPLACE_TYPE"] = "RAW",
							["VALUE_CHANGE_TABLE"] = {
								{[[MODELS\PLANETS\BIOMES\HQLUSH\HQTREES\PARTS\HQTREE23\BARK1.MATERIAL.MBIN]],[[MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\BARK.MATERIAL.MBIN]]},
								{[[MODELS\PLANETS\BIOMES\HQLUSH\HQTREES\PARTS\HQTREE23\HQFROND2.MATERIAL.MBIN]],[[MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\FROZENFRONDMAT.MATERIAL.MBIN]]},
							}
						}
					}
				},
				{--Swap HQTREE24 materials
					["MBIN_FILE_SOURCE"] = {"CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE24.SCENE.MBIN",},
					["EXML_CHANGE_TABLE"] = {
						{
							["SPECIAL_KEY_WORDS"] = {"Name","MATERIAL"},
							["REPLACE_TYPE"] = "RAW",
							["VALUE_CHANGE_TABLE"] = {
								{[[MODELS\PLANETS\BIOMES\HQLUSH\HQTREES\PARTS\HQTREE24\BARK1.MATERIAL.MBIN]],[[MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\BARK.MATERIAL.MBIN]]},
								{[[MODELS\PLANETS\BIOMES\HQLUSH\HQTREES\PARTS\HQTREE24\HQFROND3.MATERIAL.MBIN]],[[MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\FROZENFRONDMAT.MATERIAL.MBIN]]},
							}
						}
					}
				},
				{--Swap HQTREE25 materials
					["MBIN_FILE_SOURCE"] = {"CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE25.SCENE.MBIN",},
					["EXML_CHANGE_TABLE"] = {
						{
							["SPECIAL_KEY_WORDS"] = {"Name","MATERIAL"},
							["REPLACE_TYPE"] = "RAW",
							["VALUE_CHANGE_TABLE"] = {
								{[[MODELS\PLANETS\BIOMES\HQLUSH\HQTREES\PARTS\HQTREE25\BARK1.MATERIAL.MBIN]],[[MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\BARK.MATERIAL.MBIN]]},
								{[[MODELS\PLANETS\BIOMES\HQLUSH\HQTREES\PARTS\HQTREE25\HQFROND9.MATERIAL.MBIN]],[[MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\FROZENFRONDMAT.MATERIAL.MBIN]]},
							}
						}
					}
				},
				{--Swap HQTREE26 materials
					["MBIN_FILE_SOURCE"] = {"CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE26.SCENE.MBIN",},
					["EXML_CHANGE_TABLE"] = {
						{
							["SPECIAL_KEY_WORDS"] = {"Name","MATERIAL"},
							["REPLACE_TYPE"] = "RAW",
							["VALUE_CHANGE_TABLE"] = {
								{[[MODELS\PLANETS\BIOMES\HQLUSH\HQTREES\PARTS\HQTREE26\BARK1.MATERIAL.MBIN]],[[MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\BARK.MATERIAL.MBIN]]},
								{[[MODELS\PLANETS\BIOMES\HQLUSH\HQTREES\PARTS\HQTREE26\LEAF.MATERIAL.MBIN]],[[CUSTOMMODELS\CODENAMEAWESOME\BIOMES\SNOWYHQLUSH\NONBILLBOADLEAVES_NEWLEAFMAT.MATERIAL.MBIN]]},
							}
						}
					}
				},
				{--Swap HQTREE27 materials
					["MBIN_FILE_SOURCE"] = {"CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE27.SCENE.MBIN",},
					["EXML_CHANGE_TABLE"] = {
						{
							["SPECIAL_KEY_WORDS"] = {"Name","MATERIAL"},
							["REPLACE_TYPE"] = "RAW",
							["VALUE_CHANGE_TABLE"] = {
								{[[MODELS\PLANETS\BIOMES\HQLUSH\HQTREES\PARTS\HQTREE27\BARK1.MATERIAL.MBIN]],[[MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\BARK.MATERIAL.MBIN]]},
								{[[MODELS\PLANETS\BIOMES\HQLUSH\HQTREES\PARTS\HQTREE27\HQFROND1.MATERIAL.MBIN]],[[MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\FROZENFRONDMAT.MATERIAL.MBIN]]},
							}
						}
					}
				},
				{--Swap HQTREE28 materials
					["MBIN_FILE_SOURCE"] = {"CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE28.SCENE.MBIN",},
					["EXML_CHANGE_TABLE"] = {
						{
							["SPECIAL_KEY_WORDS"] = {"Name","MATERIAL"},
							["REPLACE_TYPE"] = "RAW",
							["VALUE_CHANGE_TABLE"] = {
								{[[MODELS\PLANETS\BIOMES\HQLUSH\HQTREES\PARTS\HQTREE28\BARK1.MATERIAL.MBIN]],[[MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\BARK.MATERIAL.MBIN]]},
								{[[MODELS\PLANETS\BIOMES\HQLUSH\HQTREES\PARTS\HQTREE28\HQFROND2.MATERIAL.MBIN]],[[MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\FROZENFRONDMAT.MATERIAL.MBIN]]},
							}
						}
					}
				},
				{--Swap HQTREE29 materials
					["MBIN_FILE_SOURCE"] = {"CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE29.SCENE.MBIN",},
					["EXML_CHANGE_TABLE"] = {
						{
							["SPECIAL_KEY_WORDS"] = {"Name","MATERIAL"},
							["REPLACE_TYPE"] = "RAW",
							["VALUE_CHANGE_TABLE"] = {
								{[[MODELS\PLANETS\BIOMES\HQLUSH\HQTREES\PARTS\HQTREE29\BARK1.MATERIAL.MBIN]],[[MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\BARK.MATERIAL.MBIN]]},
								{[[MODELS\PLANETS\BIOMES\HQLUSH\HQTREES\PARTS\HQTREE29\HQFROND3.MATERIAL.MBIN]],[[MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\FROZENFRONDMAT.MATERIAL.MBIN]]},
							}
						}
					}
				},
				{--Swap HQTREE30 materials
					["MBIN_FILE_SOURCE"] = {"CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE30.SCENE.MBIN",},
					["EXML_CHANGE_TABLE"] = {
						{
							["SPECIAL_KEY_WORDS"] = {"Name","MATERIAL"},
							["REPLACE_TYPE"] = "RAW",
							["VALUE_CHANGE_TABLE"] = {
								{[[MODELS\PLANETS\BIOMES\HQLUSH\HQTREES\PARTS\HQTREE30\BARK1.MATERIAL.MBIN]],[[MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\BARK.MATERIAL.MBIN]]},
								{[[MODELS\PLANETS\BIOMES\HQLUSH\HQTREES\PARTS\HQTREE30\HQFROND4.MATERIAL.MBIN]],[[MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\FROZENFRONDMAT.MATERIAL.MBIN]]},
							}
						}
					}
				},
				{--Swap HQTREE31 materials
					["MBIN_FILE_SOURCE"] = {"CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE31.SCENE.MBIN",},
					["EXML_CHANGE_TABLE"] = {
						{
							["SPECIAL_KEY_WORDS"] = {"Name","MATERIAL"},
							["REPLACE_TYPE"] = "RAW",
							["VALUE_CHANGE_TABLE"] = {
								{[[MODELS\PLANETS\BIOMES\HQLUSH\HQTREES\PARTS\HQTREE31\BARK1.MATERIAL.MBIN]],[[MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\BARK.MATERIAL.MBIN]]},
								{[[MODELS\PLANETS\BIOMES\HQLUSH\HQTREES\PARTS\HQTREE31\HQFROND6.MATERIAL.MBIN]],[[MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\FROZENFRONDMAT.MATERIAL.MBIN]]},
							}
						}
					}
				},
				{--Swap HQTREE32 materials
					["MBIN_FILE_SOURCE"] = {"CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE32.SCENE.MBIN",},
					["EXML_CHANGE_TABLE"] = {
						{
							["SPECIAL_KEY_WORDS"] = {"Name","MATERIAL"},
							["REPLACE_TYPE"] = "RAW",
							["VALUE_CHANGE_TABLE"] = {
								{[[MODELS\PLANETS\BIOMES\HQLUSH\HQTREES\PARTS\HQTREE32\BARK1.MATERIAL.MBIN]],[[MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\BARK.MATERIAL.MBIN]]},
								{[[MODELS\PLANETS\BIOMES\HQLUSH\HQTREES\PARTS\HQTREE32\HQFROND7.MATERIAL.MBIN]],[[MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\FROZENFRONDMAT.MATERIAL.MBIN]]},
							}
						}
					}
				},
				{--Swap HQTREE33 materials
					["MBIN_FILE_SOURCE"] = {"CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE33.SCENE.MBIN",},
					["EXML_CHANGE_TABLE"] = {
						{
							["SPECIAL_KEY_WORDS"] = {"Name","MATERIAL"},
							["REPLACE_TYPE"] = "RAW",
							["VALUE_CHANGE_TABLE"] = {
								{[[MODELS\PLANETS\BIOMES\HQLUSH\HQTREES\PARTS\HQTREE33\BARK1.MATERIAL.MBIN]],[[MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\BARK.MATERIAL.MBIN]]},
								{[[MODELS\PLANETS\BIOMES\HQLUSH\HQTREES\PARTS\HQTREE33\HQFROND8.MATERIAL.MBIN]],[[MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\FROZENFRONDMAT.MATERIAL.MBIN]]},
							}
						}
					}
				},
				{--Swap HQTREE34 materials
					["MBIN_FILE_SOURCE"] = {"CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE34.SCENE.MBIN",},
					["EXML_CHANGE_TABLE"] = {
						{
							["SPECIAL_KEY_WORDS"] = {"Name","MATERIAL"},
							["REPLACE_TYPE"] = "RAW",
							["VALUE_CHANGE_TABLE"] = {
								{[[MODELS\PLANETS\BIOMES\HQLUSH\HQTREES\PARTS\HQTREE34\BARK1.MATERIAL.MBIN]],[[MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\BARK.MATERIAL.MBIN]]},
								{[[MODELS\PLANETS\BIOMES\HQLUSH\HQTREES\PARTS\HQTREE34\HQFROND9.MATERIAL.MBIN]],[[MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\FROZENFRONDMAT.MATERIAL.MBIN]]},
							}
						}
					}
				},
				{--Swap HQTREE35 materials
					["MBIN_FILE_SOURCE"] = {"CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE35.SCENE.MBIN",},
					["EXML_CHANGE_TABLE"] = {
						{
							["SPECIAL_KEY_WORDS"] = {"Name","MATERIAL"},
							["REPLACE_TYPE"] = "RAW",
							["VALUE_CHANGE_TABLE"] = {
								{[[MODELS\PLANETS\BIOMES\HQLUSH\HQTREES\PARTS\HQTREE35\BARK1.MATERIAL.MBIN]],[[MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\BARK.MATERIAL.MBIN]]},
								{[[MODELS\PLANETS\BIOMES\HQLUSH\HQTREES\PARTS\HQTREE35\HQFROND10.MATERIAL.MBIN]],[[MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\FROZENFRONDMAT.MATERIAL.MBIN]]},
							}
						}
					}
				},
				{--Swap HQTREE36 materials
					["MBIN_FILE_SOURCE"] = {"CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE36.SCENE.MBIN",},
					["EXML_CHANGE_TABLE"] = {
						{
							["SPECIAL_KEY_WORDS"] = {"Name","MATERIAL"},
							["REPLACE_TYPE"] = "RAW",
							["VALUE_CHANGE_TABLE"] = {
								{[[MODELS\PLANETS\BIOMES\HQLUSH\HQTREES\PARTS\HQTREE36\BARK1.MATERIAL.MBIN]],[[MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\BARK.MATERIAL.MBIN]]},
								{[[MODELS\PLANETS\BIOMES\HQLUSH\HQTREES\PARTS\HQTREE36\LEAF.MATERIAL.MBIN]],[[CUSTOMMODELS\CODENAMEAWESOME\BIOMES\SNOWYHQLUSH\NONBILLBOADLEAVES_NEWLEAFMAT.MATERIAL.MBIN]]},
							}
						}
					}
				},
				{--Swap HQTREE37 materials
					["MBIN_FILE_SOURCE"] = {"CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE37.SCENE.MBIN",},
					["EXML_CHANGE_TABLE"] = {
						{
							["SPECIAL_KEY_WORDS"] = {"Name","MATERIAL"},
							["REPLACE_TYPE"] = "RAW",
							["VALUE_CHANGE_TABLE"] = {
								{[[MODELS\PLANETS\BIOMES\HQLUSH\HQTREES\PARTS\HQTREE37\BARK1.MATERIAL.MBIN]],[[MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\BARK.MATERIAL.MBIN]]},
								{[[MODELS\PLANETS\BIOMES\HQLUSH\HQTREES\PARTS\HQTREE37\HQFROND1.MATERIAL.MBIN]],[[MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\FROZENFRONDMAT.MATERIAL.MBIN]]},
							}
						}
					}
				},
				{--Swap HQTREE38 materials
					["MBIN_FILE_SOURCE"] = {"CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE38.SCENE.MBIN",},
					["EXML_CHANGE_TABLE"] = {
						{
							["SPECIAL_KEY_WORDS"] = {"Name","MATERIAL"},
							["REPLACE_TYPE"] = "RAW",
							["VALUE_CHANGE_TABLE"] = {
								{[[MODELS\PLANETS\BIOMES\HQLUSH\HQTREES\PARTS\HQTREE38\BARK1.MATERIAL.MBIN]],[[MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\BARK.MATERIAL.MBIN]]},
								{[[MODELS\PLANETS\BIOMES\HQLUSH\HQTREES\PARTS\HQTREE38\HQFROND2.MATERIAL.MBIN]],[[MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\FROZENFRONDMAT.MATERIAL.MBIN]]},
							}
						}
					}
				},
				{--Swap HQTREE39 materials
					["MBIN_FILE_SOURCE"] = {"CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE39.SCENE.MBIN",},
					["EXML_CHANGE_TABLE"] = {
						{
							["SPECIAL_KEY_WORDS"] = {"Name","MATERIAL"},
							["REPLACE_TYPE"] = "RAW",
							["VALUE_CHANGE_TABLE"] = {
								{[[MODELS\PLANETS\BIOMES\HQLUSH\HQTREES\PARTS\HQTREE39\BARK1.MATERIAL.MBIN]],[[MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\BARK.MATERIAL.MBIN]]},
								{[[MODELS\PLANETS\BIOMES\HQLUSH\HQTREES\PARTS\HQTREE39\HQFROND3.MATERIAL.MBIN]],[[MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\FROZENFRONDMAT.MATERIAL.MBIN]]},
							}
						}
					}
				},
				{--Swap HQTREE40 materials
					["MBIN_FILE_SOURCE"] = {"CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE40.SCENE.MBIN",},
					["EXML_CHANGE_TABLE"] = {
						{
							["SPECIAL_KEY_WORDS"] = {"Name","MATERIAL"},
							["REPLACE_TYPE"] = "RAW",
							["VALUE_CHANGE_TABLE"] = {
								{[[MODELS\PLANETS\BIOMES\HQLUSH\HQTREES\PARTS\HQTREE40\BARK1.MATERIAL.MBIN]],[[MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\BARK.MATERIAL.MBIN]]},
								{[[MODELS\PLANETS\BIOMES\HQLUSH\HQTREES\PARTS\HQTREE40\HQFROND4.MATERIAL.MBIN]],[[MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\FROZENFRONDMAT.MATERIAL.MBIN]]},
							}
						}
					}
				},
				{--Swap HQTREE41 materials
					["MBIN_FILE_SOURCE"] = {"CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE41.SCENE.MBIN",},
					["EXML_CHANGE_TABLE"] = {
						{
							["SPECIAL_KEY_WORDS"] = {"Name","MATERIAL"},
							["REPLACE_TYPE"] = "RAW",
							["VALUE_CHANGE_TABLE"] = {
								{[[MODELS\PLANETS\BIOMES\HQLUSH\HQTREES\PARTS\HQTREE41\BARK1.MATERIAL.MBIN]],[[MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\BARK.MATERIAL.MBIN]]},
								{[[MODELS\PLANETS\BIOMES\HQLUSH\HQTREES\PARTS\HQTREE41\HQFROND6.MATERIAL.MBIN]],[[MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\FROZENFRONDMAT.MATERIAL.MBIN]]},
							}
						}
					}
				},
				{--Swap HQTREE42 materials
					["MBIN_FILE_SOURCE"] = {"CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE42.SCENE.MBIN",},
					["EXML_CHANGE_TABLE"] = {
						{
							["SPECIAL_KEY_WORDS"] = {"Name","MATERIAL"},
							["REPLACE_TYPE"] = "RAW",
							["VALUE_CHANGE_TABLE"] = {
								{[[MODELS\PLANETS\BIOMES\HQLUSH\HQTREES\PARTS\HQTREE42\BARK1.MATERIAL.MBIN]],[[MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\BARK.MATERIAL.MBIN]]},
								{[[MODELS\PLANETS\BIOMES\HQLUSH\HQTREES\PARTS\HQTREE42\HQFROND7.MATERIAL.MBIN]],[[MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\FROZENFRONDMAT.MATERIAL.MBIN]]},
							}
						}
					}
				},
				{--Swap HQTREE43 materials
					["MBIN_FILE_SOURCE"] = {"CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE43.SCENE.MBIN",},
					["EXML_CHANGE_TABLE"] = {
						{
							["SPECIAL_KEY_WORDS"] = {"Name","MATERIAL"},
							["REPLACE_TYPE"] = "RAW",
							["VALUE_CHANGE_TABLE"] = {
								{[[MODELS\PLANETS\BIOMES\HQLUSH\HQTREES\PARTS\HQTREE43\BARK1.MATERIAL.MBIN]],[[MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\BARK.MATERIAL.MBIN]]},
								{[[MODELS\PLANETS\BIOMES\HQLUSH\HQTREES\PARTS\HQTREE43\HQFROND9.MATERIAL.MBIN]],[[MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\FROZENFRONDMAT.MATERIAL.MBIN]]},
							}
						}
					}
				},
				{--Swap HQTREE44 materials
					["MBIN_FILE_SOURCE"] = {"CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE44.SCENE.MBIN",},
					["EXML_CHANGE_TABLE"] = {
						{
							["SPECIAL_KEY_WORDS"] = {"Name","MATERIAL"},
							["REPLACE_TYPE"] = "RAW",
							["VALUE_CHANGE_TABLE"] = {
								{[[MODELS\PLANETS\BIOMES\HQLUSH\HQTREES\PARTS\HQTREE44\BARK1.MATERIAL.MBIN]],[[MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\BARK.MATERIAL.MBIN]]},
								{[[MODELS\PLANETS\BIOMES\HQLUSH\HQTREES\PARTS\HQTREE44\HQFROND10.MATERIAL.MBIN]],[[MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\FROZENFRONDMAT.MATERIAL.MBIN]]},
							}
						}
					}
				},
				{--Swap HQTREE45 materials
					["MBIN_FILE_SOURCE"] = {"CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE45.SCENE.MBIN",},
					["EXML_CHANGE_TABLE"] = {
						{
							["SPECIAL_KEY_WORDS"] = {"Name","MATERIAL"},
							["REPLACE_TYPE"] = "RAW",
							["VALUE_CHANGE_TABLE"] = {
								{[[MODELS\PLANETS\BIOMES\HQLUSH\HQTREES\PARTS\HQTREE45\BARK1.MATERIAL.MBIN]],[[MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\BARK.MATERIAL.MBIN]]},
								{[[MODELS\PLANETS\BIOMES\HQLUSH\HQTREES\PARTS\HQTREE45\LEAF.MATERIAL.MBIN]],[[CUSTOMMODELS\CODENAMEAWESOME\BIOMES\SNOWYHQLUSH\NONBILLBOADLEAVES_NEWLEAFMAT.MATERIAL.MBIN]]},
							}
						}
					}
				},
				{--Swap HQTREE46 materials
					["MBIN_FILE_SOURCE"] = {"CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE46.SCENE.MBIN",},
					["EXML_CHANGE_TABLE"] = {
						{
							["SPECIAL_KEY_WORDS"] = {"Name","MATERIAL"},
							["REPLACE_TYPE"] = "RAW",
							["VALUE_CHANGE_TABLE"] = {
								{[[MODELS\PLANETS\BIOMES\HQLUSH\HQTREES\PARTS\HQTREE46\BARK1.MATERIAL.MBIN]],[[MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\BARK.MATERIAL.MBIN]]},
								{[[MODELS\PLANETS\BIOMES\HQLUSH\HQTREES\PARTS\HQTREE46\LEAF.MATERIAL.MBIN]],[[CUSTOMMODELS\CODENAMEAWESOME\BIOMES\SNOWYHQLUSH\NONBILLBOADLEAVES_NEWLEAFMAT.MATERIAL.MBIN]]},
							}
						}
					}
				},
				{--Swap HQTREE47 materials
					["MBIN_FILE_SOURCE"] = {"CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE47.SCENE.MBIN",},
					["EXML_CHANGE_TABLE"] = {
						{
							["SPECIAL_KEY_WORDS"] = {"Name","MATERIAL"},
							["REPLACE_TYPE"] = "RAW",
							["VALUE_CHANGE_TABLE"] = {
								{[[MODELS\PLANETS\BIOMES\HQLUSH\HQTREES\PARTS\HQTREE47\BARK11.MATERIAL.MBIN]],[[MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\BARK.MATERIAL.MBIN]]},
							}
						}
					}
				},
				{--Swap HQTREE48 materials
					["MBIN_FILE_SOURCE"] = {"CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE48.SCENE.MBIN",},
					["EXML_CHANGE_TABLE"] = {
						{
							["SPECIAL_KEY_WORDS"] = {"Name","MATERIAL"},
							["REPLACE_TYPE"] = "RAW",
							["VALUE_CHANGE_TABLE"] = {
								{[[MODELS\PLANETS\BIOMES\HQLUSH\HQTREES\PARTS\HQTREE48\BARK1.MATERIAL.MBIN]],[[MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\BARK.MATERIAL.MBIN]]},
								{[[MODELS\PLANETS\BIOMES\HQLUSH\HQTREES\PARTS\HQTREE48\HQFROND1.MATERIAL.MBIN]],[[MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\FROZENFRONDMAT.MATERIAL.MBIN]]},
							}
						}
					}
				},
				{--Swap HQTREE49 materials
					["MBIN_FILE_SOURCE"] = {"CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE49.SCENE.MBIN",},
					["EXML_CHANGE_TABLE"] = {
						{
							["SPECIAL_KEY_WORDS"] = {"Name","MATERIAL"},
							["REPLACE_TYPE"] = "RAW",
							["VALUE_CHANGE_TABLE"] = {
								{[[MODELS\PLANETS\BIOMES\HQLUSH\HQTREES\PARTS\HQTREE49\BARK1.MATERIAL.MBIN]],[[MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\BARK.MATERIAL.MBIN]]},
								{[[MODELS\PLANETS\BIOMES\HQLUSH\HQTREES\PARTS\HQTREE49\HQFROND2.MATERIAL.MBIN]],[[MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\FROZENFRONDMAT.MATERIAL.MBIN]]},
							}
						}
					}
				},
				{--Swap HQTREE50 materials
					["MBIN_FILE_SOURCE"] = {"CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE50.SCENE.MBIN",},
					["EXML_CHANGE_TABLE"] = {
						{
							["SPECIAL_KEY_WORDS"] = {"Name","MATERIAL"},
							["REPLACE_TYPE"] = "RAW",
							["VALUE_CHANGE_TABLE"] = {
								{[[MODELS\PLANETS\BIOMES\HQLUSH\HQTREES\PARTS\HQTREE50\BARK1.MATERIAL.MBIN]],[[MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\BARK.MATERIAL.MBIN]]},
								{[[MODELS\PLANETS\BIOMES\HQLUSH\HQTREES\PARTS\HQTREE50\HQFROND3.MATERIAL.MBIN]],[[MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\FROZENFRONDMAT.MATERIAL.MBIN]]},
							}
						}
					}
				},
				{--Swap HQTREE51 materials
					["MBIN_FILE_SOURCE"] = {"CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE51.SCENE.MBIN",},
					["EXML_CHANGE_TABLE"] = {
						{
							["SPECIAL_KEY_WORDS"] = {"Name","MATERIAL"},
							["REPLACE_TYPE"] = "RAW",
							["VALUE_CHANGE_TABLE"] = {
								{[[MODELS\PLANETS\BIOMES\HQLUSH\HQTREES\PARTS\HQTREE51\BARK1.MATERIAL.MBIN]],[[MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\BARK.MATERIAL.MBIN]]},
								{[[MODELS\PLANETS\BIOMES\HQLUSH\HQTREES\PARTS\HQTREE51\HQFROND4.MATERIAL.MBIN]],[[MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\FROZENFRONDMAT.MATERIAL.MBIN]]},
							}
						}
					}
				},
				{--Swap HQTREE52 materials
					["MBIN_FILE_SOURCE"] = {"CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE52.SCENE.MBIN",},
					["EXML_CHANGE_TABLE"] = {
						{
							["SPECIAL_KEY_WORDS"] = {"Name","MATERIAL"},
							["REPLACE_TYPE"] = "RAW",
							["VALUE_CHANGE_TABLE"] = {
								{[[MODELS\PLANETS\BIOMES\HQLUSH\HQTREES\PARTS\HQTREE52\BARK1.MATERIAL.MBIN]],[[MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\BARK.MATERIAL.MBIN]]},
								{[[MODELS\PLANETS\BIOMES\HQLUSH\HQTREES\PARTS\HQTREE52\HQFROND5.MATERIAL.MBIN]],[[MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\FROZENFRONDMAT.MATERIAL.MBIN]]},
							}
						}
					}
				},
				{--Swap HQTREE53 materials
					["MBIN_FILE_SOURCE"] = {"CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE53.SCENE.MBIN",},
					["EXML_CHANGE_TABLE"] = {
						{
							["SPECIAL_KEY_WORDS"] = {"Name","MATERIAL"},
							["REPLACE_TYPE"] = "RAW",
							["VALUE_CHANGE_TABLE"] = {
								{[[MODELS\PLANETS\BIOMES\HQLUSH\HQTREES\PARTS\HQTREE53\BARK1.MATERIAL.MBIN]],[[MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\BARK.MATERIAL.MBIN]]},
								{[[MODELS\PLANETS\BIOMES\HQLUSH\HQTREES\PARTS\HQTREE53\HQFROND6.MATERIAL.MBIN]],[[MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\FROZENFRONDMAT.MATERIAL.MBIN]]},
							}
						}
					}
				},
				{--Swap HQTREE54 materials
					["MBIN_FILE_SOURCE"] = {"CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE54.SCENE.MBIN",},
					["EXML_CHANGE_TABLE"] = {
						{
							["SPECIAL_KEY_WORDS"] = {"Name","MATERIAL"},
							["REPLACE_TYPE"] = "RAW",
							["VALUE_CHANGE_TABLE"] = {
								{[[MODELS\PLANETS\BIOMES\HQLUSH\HQTREES\PARTS\HQTREE54\BARK1.MATERIAL.MBIN]],[[MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\BARK.MATERIAL.MBIN]]},
								{[[MODELS\PLANETS\BIOMES\HQLUSH\HQTREES\PARTS\HQTREE54\HQFROND7.MATERIAL.MBIN]],[[MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\FROZENFRONDMAT.MATERIAL.MBIN]]},
							}
						}
					}
				},
				{--Swap HQTREE55 materials
					["MBIN_FILE_SOURCE"] = {"CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE55.SCENE.MBIN",},
					["EXML_CHANGE_TABLE"] = {
						{
							["SPECIAL_KEY_WORDS"] = {"Name","MATERIAL"},
							["REPLACE_TYPE"] = "RAW",
							["VALUE_CHANGE_TABLE"] = {
								{[[MODELS\PLANETS\BIOMES\HQLUSH\HQTREES\PARTS\HQTREE55\BARK1.MATERIAL.MBIN]],[[MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\BARK.MATERIAL.MBIN]]},
								{[[MODELS\PLANETS\BIOMES\HQLUSH\HQTREES\PARTS\HQTREE55\HQFROND9.MATERIAL.MBIN]],[[MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\FROZENFRONDMAT.MATERIAL.MBIN]]},
							}
						}
					}
				},
				{--Swap HQTREE56 materials
					["MBIN_FILE_SOURCE"] = {"CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE56.SCENE.MBIN",},
					["EXML_CHANGE_TABLE"] = {
						{
							["SPECIAL_KEY_WORDS"] = {"Name","MATERIAL"},
							["REPLACE_TYPE"] = "RAW",
							["VALUE_CHANGE_TABLE"] = {
								{[[MODELS\PLANETS\BIOMES\HQLUSH\HQTREES\PARTS\HQTREE56\BARK1.MATERIAL.MBIN]],[[MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\BARK.MATERIAL.MBIN]]},
								{[[MODELS\PLANETS\BIOMES\HQLUSH\HQTREES\PARTS\HQTREE56\LEAF.MATERIAL.MBIN]],[[CUSTOMMODELS\CODENAMEAWESOME\BIOMES\SNOWYHQLUSH\NONBILLBOADLEAVES_NEWLEAFMAT.MATERIAL.MBIN]]},
							}
						}
					}
				},
				{--Swap HQTREE57 materials
					["MBIN_FILE_SOURCE"] = {"CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE57.SCENE.MBIN",},
					["EXML_CHANGE_TABLE"] = {
						{
							["SPECIAL_KEY_WORDS"] = {"Name","MATERIAL"},
							["REPLACE_TYPE"] = "RAW",
							["VALUE_CHANGE_TABLE"] = {
								{[[MODELS\PLANETS\BIOMES\HQLUSH\HQTREES\PARTS\HQTREE57\BARK1.MATERIAL.MBIN]],[[MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\BARK.MATERIAL.MBIN]]},
								{[[MODELS\PLANETS\BIOMES\HQLUSH\HQTREES\PARTS\HQTREE57\HQFROND2.MATERIAL.MBIN]],[[MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\FROZENFRONDMAT.MATERIAL.MBIN]]},
							}
						}
					}
				},
				{--Swap HQTREE58 materials
					["MBIN_FILE_SOURCE"] = {"CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE58.SCENE.MBIN",},
					["EXML_CHANGE_TABLE"] = {
						{
							["SPECIAL_KEY_WORDS"] = {"Name","MATERIAL"},
							["REPLACE_TYPE"] = "RAW",
							["VALUE_CHANGE_TABLE"] = {
								{[[MODELS\PLANETS\BIOMES\HQLUSH\HQTREES\PARTS\HQTREE58\BARK1.MATERIAL.MBIN]],[[MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\BARK.MATERIAL.MBIN]]},
								{[[MODELS\PLANETS\BIOMES\HQLUSH\HQTREES\PARTS\HQTREE58\HQFROND3.MATERIAL.MBIN]],[[MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\FROZENFRONDMAT.MATERIAL.MBIN]]},
							}
						}
					}
				},
				{--Swap HQTREE59 materials
					["MBIN_FILE_SOURCE"] = {"CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE59.SCENE.MBIN",},
					["EXML_CHANGE_TABLE"] = {
						{
							["SPECIAL_KEY_WORDS"] = {"Name","MATERIAL"},
							["REPLACE_TYPE"] = "RAW",
							["VALUE_CHANGE_TABLE"] = {
								{[[MODELS\PLANETS\BIOMES\HQLUSH\HQTREES\PARTS\HQTREE59\BARK1.MATERIAL.MBIN]],[[MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\BARK.MATERIAL.MBIN]]},
								{[[MODELS\PLANETS\BIOMES\HQLUSH\HQTREES\PARTS\HQTREE59\HQFROND4.MATERIAL.MBIN]],[[MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\FROZENFRONDMAT.MATERIAL.MBIN]]},
							}
						}
					}
				},
				{--Swap HQTREE60 materials
					["MBIN_FILE_SOURCE"] = {"CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE60.SCENE.MBIN",},
					["EXML_CHANGE_TABLE"] = {
						{
							["SPECIAL_KEY_WORDS"] = {"Name","MATERIAL"},
							["REPLACE_TYPE"] = "RAW",
							["VALUE_CHANGE_TABLE"] = {
								{[[MODELS\PLANETS\BIOMES\HQLUSH\HQTREES\PARTS\HQTREE60\BARK1.MATERIAL.MBIN]],[[MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\BARK.MATERIAL.MBIN]]},
								{[[MODELS\PLANETS\BIOMES\HQLUSH\HQTREES\PARTS\HQTREE60\HQFROND6.MATERIAL.MBIN]],[[MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\FROZENFRONDMAT.MATERIAL.MBIN]]},
							}
						}
					}
				},
				{--Swap HQTREE61 materials
					["MBIN_FILE_SOURCE"] = {"CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE61.SCENE.MBIN",},
					["EXML_CHANGE_TABLE"] = {
						{
							["SPECIAL_KEY_WORDS"] = {"Name","MATERIAL"},
							["REPLACE_TYPE"] = "RAW",
							["VALUE_CHANGE_TABLE"] = {
								{[[MODELS\PLANETS\BIOMES\HQLUSH\HQTREES\PARTS\HQTREE61\BARK1.MATERIAL.MBIN]],[[MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\BARK.MATERIAL.MBIN]]},
								{[[MODELS\PLANETS\BIOMES\HQLUSH\HQTREES\PARTS\HQTREE61\HQFROND7.MATERIAL.MBIN]],[[MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\FROZENFRONDMAT.MATERIAL.MBIN]]},
							}
						}
					}
				},
				{--Swap HQTREE62 materials
					["MBIN_FILE_SOURCE"] = {"CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE62.SCENE.MBIN",},
					["EXML_CHANGE_TABLE"] = {
						{
							["SPECIAL_KEY_WORDS"] = {"Name","MATERIAL"},
							["REPLACE_TYPE"] = "RAW",
							["VALUE_CHANGE_TABLE"] = {
								{[[MODELS\PLANETS\BIOMES\HQLUSH\HQTREES\PARTS\HQTREE62\BARK1.MATERIAL.MBIN]],[[MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\BARK.MATERIAL.MBIN]]},
								{[[MODELS\PLANETS\BIOMES\HQLUSH\HQTREES\PARTS\HQTREE62\HQFROND9.MATERIAL.MBIN]],[[MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\FROZENFRONDMAT.MATERIAL.MBIN]]},
							}
						}
					}
				},
				{--Swap HQTREE63 materials
					["MBIN_FILE_SOURCE"] = {"CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE63.SCENE.MBIN",},
					["EXML_CHANGE_TABLE"] = {
						{
							["SPECIAL_KEY_WORDS"] = {"Name","MATERIAL"},
							["REPLACE_TYPE"] = "RAW",
							["VALUE_CHANGE_TABLE"] = {
								{[[MODELS\PLANETS\BIOMES\HQLUSH\HQTREES\PARTS\HQTREE63\BARK1.MATERIAL.MBIN]],[[MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\BARK.MATERIAL.MBIN]]},
								{[[MODELS\PLANETS\BIOMES\HQLUSH\HQTREES\PARTS\HQTREE63\HQFROND10.MATERIAL.MBIN]],[[MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\FROZENFRONDMAT.MATERIAL.MBIN]]},
							}
						}
					}
				},
				{--Swap HQTREE64 materials
					["MBIN_FILE_SOURCE"] = {"CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE64.SCENE.MBIN",},
					["EXML_CHANGE_TABLE"] = {
						{
							["SPECIAL_KEY_WORDS"] = {"Name","MATERIAL"},
							["REPLACE_TYPE"] = "RAW",
							["VALUE_CHANGE_TABLE"] = {
								{[[MODELS\PLANETS\BIOMES\HQLUSH\HQTREES\PARTS\HQTREE64\BARK1.MATERIAL.MBIN]],[[MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\BARK.MATERIAL.MBIN]]},
								{[[MODELS\PLANETS\BIOMES\HQLUSH\HQTREES\PARTS\HQTREE64\LEAF.MATERIAL.MBIN]],[[CUSTOMMODELS\CODENAMEAWESOME\BIOMES\SNOWYHQLUSH\NONBILLBOADLEAVES_NEWLEAFMAT.MATERIAL.MBIN]]},
							}
						}
					}
				},
				{--Swap HQTREE65 materials
					["MBIN_FILE_SOURCE"] = {"CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE65.SCENE.MBIN",},
					["EXML_CHANGE_TABLE"] = {
						{
							["SPECIAL_KEY_WORDS"] = {"Name","MATERIAL"},
							["REPLACE_TYPE"] = "RAW",
							["VALUE_CHANGE_TABLE"] = {
								{[[MODELS\PLANETS\BIOMES\HQLUSH\HQTREES\PARTS\HQTREE65\BARK11.MATERIAL.MBIN]],[[MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\BARK.MATERIAL.MBIN]]},
							}
						}
					}
				},
				{--Swap HQTREE66 materials
					["MBIN_FILE_SOURCE"] = {"CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE66.SCENE.MBIN",},
					["EXML_CHANGE_TABLE"] = {
						{
							["SPECIAL_KEY_WORDS"] = {"Name","MATERIAL"},
							["REPLACE_TYPE"] = "RAW",
							["VALUE_CHANGE_TABLE"] = {
								{[[MODELS\PLANETS\BIOMES\HQLUSH\HQTREES\PARTS\HQTREE66\BARK11.MATERIAL.MBIN]],[[MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\BARK.MATERIAL.MBIN]]},
							}
						}
					}
				},
				{--Swap HQTREE67 materials
					["MBIN_FILE_SOURCE"] = {"CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE67.SCENE.MBIN",},
					["EXML_CHANGE_TABLE"] = {
						{
							["SPECIAL_KEY_WORDS"] = {"Name","MATERIAL"},
							["REPLACE_TYPE"] = "RAW",
							["VALUE_CHANGE_TABLE"] = {
								{[[MODELS\PLANETS\BIOMES\HQLUSH\HQTREES\PARTS\HQTREE67\BARK11.MATERIAL.MBIN]],[[MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\BARK.MATERIAL.MBIN]]},
							}
						}
					}
				},
				{--Swap HQTREE68 materials
					["MBIN_FILE_SOURCE"] = {"CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE68.SCENE.MBIN",},
					["EXML_CHANGE_TABLE"] = {
						{
							["SPECIAL_KEY_WORDS"] = {"Name","MATERIAL"},
							["REPLACE_TYPE"] = "RAW",
							["VALUE_CHANGE_TABLE"] = {
								{[[MODELS\PLANETS\BIOMES\HQLUSH\HQTREES\PARTS\HQTREE68\BARK1.MATERIAL.MBIN]],[[MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\BARK.MATERIAL.MBIN]]},
								{[[MODELS\PLANETS\BIOMES\HQLUSH\HQTREES\PARTS\HQTREE68\HQFROND1.MATERIAL.MBIN]],[[MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\FROZENFRONDMAT.MATERIAL.MBIN]]},
							}
						}
					}
				},
				{--Swap HQTREE69 materials
					["MBIN_FILE_SOURCE"] = {"CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE69.SCENE.MBIN",},
					["EXML_CHANGE_TABLE"] = {
						{
							["SPECIAL_KEY_WORDS"] = {"Name","MATERIAL"},
							["REPLACE_TYPE"] = "RAW",
							["VALUE_CHANGE_TABLE"] = {
								{[[MODELS\PLANETS\BIOMES\HQLUSH\HQTREES\PARTS\HQTREE69\BARK1.MATERIAL.MBIN]],[[MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\BARK.MATERIAL.MBIN]]},
								{[[MODELS\PLANETS\BIOMES\HQLUSH\HQTREES\PARTS\HQTREE69\HQFROND2.MATERIAL.MBIN]],[[MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\FROZENFRONDMAT.MATERIAL.MBIN]]},
							}
						}
					}
				},
				{--Swap HQTREE70 materials
					["MBIN_FILE_SOURCE"] = {"CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE70.SCENE.MBIN",},
					["EXML_CHANGE_TABLE"] = {
						{
							["SPECIAL_KEY_WORDS"] = {"Name","MATERIAL"},
							["REPLACE_TYPE"] = "RAW",
							["VALUE_CHANGE_TABLE"] = {
								{[[MODELS\PLANETS\BIOMES\HQLUSH\HQTREES\PARTS\HQTREE70\BARK1.MATERIAL.MBIN]],[[MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\BARK.MATERIAL.MBIN]]},
								{[[MODELS\PLANETS\BIOMES\HQLUSH\HQTREES\PARTS\HQTREE70\HQFROND3.MATERIAL.MBIN]],[[MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\FROZENFRONDMAT.MATERIAL.MBIN]]},
							}
						}
					}
				},
				{--Swap HQTREE71 materials
					["MBIN_FILE_SOURCE"] = {"CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE71.SCENE.MBIN",},
					["EXML_CHANGE_TABLE"] = {
						{
							["SPECIAL_KEY_WORDS"] = {"Name","MATERIAL"},
							["REPLACE_TYPE"] = "RAW",
							["VALUE_CHANGE_TABLE"] = {
								{[[MODELS\PLANETS\BIOMES\HQLUSH\HQTREES\PARTS\HQTREE71\BARK1.MATERIAL.MBIN]],[[MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\BARK.MATERIAL.MBIN]]},
								{[[MODELS\PLANETS\BIOMES\HQLUSH\HQTREES\PARTS\HQTREE71\HQFROND4.MATERIAL.MBIN]],[[MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\FROZENFRONDMAT.MATERIAL.MBIN]]},
							}
						}
					}
				},
				{--Swap HQTREE72 materials
					["MBIN_FILE_SOURCE"] = {"CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE72.SCENE.MBIN",},
					["EXML_CHANGE_TABLE"] = {
						{
							["SPECIAL_KEY_WORDS"] = {"Name","MATERIAL"},
							["REPLACE_TYPE"] = "RAW",
							["VALUE_CHANGE_TABLE"] = {
								{[[MODELS\PLANETS\BIOMES\HQLUSH\HQTREES\PARTS\HQTREE72\BARK1.MATERIAL.MBIN]],[[MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\BARK.MATERIAL.MBIN]]},
								{[[MODELS\PLANETS\BIOMES\HQLUSH\HQTREES\PARTS\HQTREE72\HQFROND6.MATERIAL.MBIN]],[[MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\FROZENFRONDMAT.MATERIAL.MBIN]]},
							}
						}
					}
				},
				{--Swap HQTREE73 materials
					["MBIN_FILE_SOURCE"] = {"CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE73.SCENE.MBIN",},
					["EXML_CHANGE_TABLE"] = {
						{
							["SPECIAL_KEY_WORDS"] = {"Name","MATERIAL"},
							["REPLACE_TYPE"] = "RAW",
							["VALUE_CHANGE_TABLE"] = {
								{[[MODELS\PLANETS\BIOMES\HQLUSH\HQTREES\PARTS\HQTREE73\BARK1.MATERIAL.MBIN]],[[MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\BARK.MATERIAL.MBIN]]},
								{[[MODELS\PLANETS\BIOMES\HQLUSH\HQTREES\PARTS\HQTREE73\HQFROND7.MATERIAL.MBIN]],[[MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\FROZENFRONDMAT.MATERIAL.MBIN]]},
							}
						}
					}
				},
				{--Swap HQTREE74 materials
					["MBIN_FILE_SOURCE"] = {"CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE74.SCENE.MBIN",},
					["EXML_CHANGE_TABLE"] = {
						{
							["SPECIAL_KEY_WORDS"] = {"Name","MATERIAL"},
							["REPLACE_TYPE"] = "RAW",
							["VALUE_CHANGE_TABLE"] = {
								{[[MODELS\PLANETS\BIOMES\HQLUSH\HQTREES\PARTS\HQTREE74\BARK1.MATERIAL.MBIN]],[[MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\BARK.MATERIAL.MBIN]]},
								{[[MODELS\PLANETS\BIOMES\HQLUSH\HQTREES\PARTS\HQTREE74\HQFROND9.MATERIAL.MBIN]],[[MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\FROZENFRONDMAT.MATERIAL.MBIN]]},
							}
						}
					}
				},
				{--Swap HQTREE75 materials
					["MBIN_FILE_SOURCE"] = {"CUSTOMMODELS/CODENAMEAWESOME/BIOMES/SNOWYHQLUSH/HQTREES/PARTS/HQTREE75.SCENE.MBIN",},
					["EXML_CHANGE_TABLE"] = {
						{
							["SPECIAL_KEY_WORDS"] = {"Name","MATERIAL"},
							["REPLACE_TYPE"] = "RAW",
							["VALUE_CHANGE_TABLE"] = {
								{[[MODELS\PLANETS\BIOMES\HQLUSH\HQTREES\PARTS\HQTREE75\BARK1.MATERIAL.MBIN]],[[MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\BARK.MATERIAL.MBIN]]},
								{[[MODELS\PLANETS\BIOMES\HQLUSH\HQTREES\PARTS\HQTREE75\LEAF.MATERIAL.MBIN]],[[CUSTOMMODELS\CODENAMEAWESOME\BIOMES\SNOWYHQLUSH\NONBILLBOADLEAVES_NEWLEAFMAT.MATERIAL.MBIN]]},
							}
						}
					}
				},
			}
		},
	}
}
--NOTE: ANYTHING NOT in table NMS_MOD_DEFINITION_CONTAINER IS IGNORED AFTER THE SCRIPT IS LOADED
--IT IS BETTER TO ADD THINGS AT THE TOP IF YOU NEED TO
--DON'T ADD ANYTHING PASS THIS POINT HERE