NMS_MOD_DEFINITION_CONTAINER = 
{
  ["MOD_BATCHNAME"] 			= "zzCodenameAwesome-Assets.pak",
  ["MOD_FILENAME"] 			= "zzCodenameAwesome-Assets-SnowyRadio.pak",
  ["MOD_DESCRIPTION"]		= "Copies the radioactive Tree models and swaps the materials for frozen ones.",
  ["MOD_AUTHOR"]				= "",
  ["NMS_VERSION"]				= "3.13",
  ["MODIFICATIONS"] 		=
	{
		{
			["MBIN_CHANGE_TABLE"] =  {
				{--Create the model
					["MBIN_FILE_SOURCE"] = {
						{"MODELS/PLANETS/BIOMES/RADIOACTIVE/LARGE/RADIOACTIVETREE.DESCRIPTOR.MBIN","CUSTOMMODELS/BIOMES/SNOWYRADIOACTIVE/LARGE/RADIOACTIVETREE.DESCRIPTOR.MBIN","REMOVE"},
						{"MODELS/PLANETS/BIOMES/RADIOACTIVE/LARGE/RADIOACTIVETREE.SCENE.MBIN","CUSTOMMODELS/BIOMES/SNOWYRADIOACTIVE/LARGE/RADIOACTIVETREE.SCENE.MBIN","REMOVE"},
					}
				},
				{
					["MBIN_FILE_SOURCE"] = {"CUSTOMMODELS/BIOMES/SNOWYRADIOACTIVE/LARGE/RADIOACTIVETREE.SCENE.MBIN"},
					["EXML_CHANGE_TABLE"] = {
						{
							["SPECIAL_KEY_WORDS"] = {"Name","MATERIAL"},
							["REPLACE_TYPE"] = "RAW",
							["VALUE_CHANGE_TABLE"] = {
								--{[[MODELS\PLANETS\BIOMES\RADIOACTIVE\LARGE\RADIOACTIVETREE\GROWTHMAT.MATERIAL.MBIN]],[[]]},
								--{[[MODELS\PLANETS\BIOMES\RADIOACTIVE\LARGE\RADIOACTIVETREE\IMPOST_IMPOSTERMAT.MATERIAL.MBIN]],[[]]},
								{[[MODELS\PLANETS\BIOMES\RADIOACTIVE\LARGE\RADIOACTIVETREE\RADIATIONBARKMAT.MATERIAL.MBIN]],[[MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\BARK.MATERIAL.MBIN]]},
								{[[MODELS\PLANETS\BIOMES\RADIOACTIVE\LARGE\RADIOACTIVETREE\RADLEAFMAT.MATERIAL.MBIN]],[[MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\FROZENFRONDMAT.MATERIAL.MBIN]]},
								--{[[MODELS\PLANETS\BIOMES\RADIOACTIVE\LARGE\RADIOACTIVETREE\VINETEST.MATERIAL.MBIN]],[[]]},
							},
						}
					}
				},
			}
		},
	}
}
--NOTE: ANYTHING NOT in table NMS_MOD_DEFINITION_CONTAINER IS IGNORED AFTER THE SCRIPT IS LOADED
--IT IS BETTER TO ADD THINGS AT THE TOP IF YOU NEED TO
--DON'T ADD ANYTHING PASS THIS POINT HERE