NMS_UNPACKED_DIR = "D:/NMSUnpackedNEXTGEN/" --Make sure you have the slash at the end. You need to have your game unpacked and listed here for this script to work.
--Currently filepaths are kinda messed up in AMUMSS at the moment. If you have issues. Try putting your unpacked files into your ModScript folder and changing this to a relative filepath.
NMS_MOD_DEFINITION_CONTAINER = 
{
  ["MOD_BATCHNAME"] 			= "zzCodenameAwesome-Assets.pak",
  ["MOD_DESCRIPTION"]		= "Copies all the assets from the Frozen biome and removes the snow textures, creating new alpine assets.",
  ["MOD_FILENAME"] 			= "zzCodenameAwesome-Assets-DeFrozenObjects.pak",
  ["MOD_AUTHOR"]				= "CodenameAwesome",
  ["NMS_VERSION"]				= "3.13",
  ["ADD_FILES"] = 
  {
    {--Large TilingRock
      ["EXTERNAL_FILE_SOURCE"] = ""..NMS_UNPACKED_DIR.."TEXTURES/PLANETS/BIOMES/FROZEN/LARGEPROPS/TILINGROCKA.BASE.1.DDS",
      ["FILE_DESTINATION"] = "CUSTOMTEXTURES/CODENAMEAWESOME/BIOMES/DEFROZEN/LARGEPROPS/"
    },
	 {--SmoothRockTiling
      ["EXTERNAL_FILE_SOURCE"] = ""..NMS_UNPACKED_DIR.."TEXTURES/PLANETS/BIOMES/FROZEN/LARGEPROPS/SMOOTHROCKTILING.DDS",
      ["FILE_DESTINATION"] = "CUSTOMTEXTURES/CODENAMEAWESOME/BIOMES/DEFROZEN/LARGEPROPS/"
    },
	{--Tree billboards
      ["EXTERNAL_FILE_SOURCE"] = ""..NMS_UNPACKED_DIR.."TEXTURES/PLANETS/BIOMES/FROZEN/LARGEPROPS/SNOWBILLLEAF.BASE.1.DDS",
      ["FILE_DESTINATION"] = "CUSTOMTEXTURES/CODENAMEAWESOME/BIOMES/DEFROZEN/LARGEPROPS/"
    },
	{--Tree fronds 1
      ["EXTERNAL_FILE_SOURCE"] = ""..NMS_UNPACKED_DIR.."TEXTURES/PLANETS/BIOMES/FROZEN/LARGEPROPS/SNOWFROND.BASE.1.DDS",
      ["FILE_DESTINATION"] = "CUSTOMTEXTURES/CODENAMEAWESOME/BIOMES/DEFROZEN/LARGEPROPS/"
    },
	{--Tree fronds 2
      ["EXTERNAL_FILE_SOURCE"] = ""..NMS_UNPACKED_DIR.."TEXTURES/PLANETS/BIOMES/FROZEN/LARGEPROPS/SNOWFROND.BASE.2.DDS",
      ["FILE_DESTINATION"] = "CUSTOMTEXTURES/CODENAMEAWESOME/BIOMES/DEFROZEN/LARGEPROPS/"
    },
	{--Tree base
      ["EXTERNAL_FILE_SOURCE"] = ""..NMS_UNPACKED_DIR.."TEXTURES/PLANETS/BIOMES/FROZEN/LARGEPROPS/TREEBASE.DDS",
      ["FILE_DESTINATION"] = "CUSTOMTEXTURES/CODENAMEAWESOME/BIOMES/DEFROZEN/LARGEPROPS/"
    },
	{--Tree base
      ["EXTERNAL_FILE_SOURCE"] = ""..NMS_UNPACKED_DIR.."TEXTURES/PLANETS/BIOMES/FROZEN/LARGEPROPS/TREEBASE.BASE.1.DDS",
      ["FILE_DESTINATION"] = "CUSTOMTEXTURES/CODENAMEAWESOME/BIOMES/DEFROZEN/LARGEPROPS/"
    },
	{--Tree bark
      ["EXTERNAL_FILE_SOURCE"] = ""..NMS_UNPACKED_DIR.."TEXTURES/PLANETS/BIOMES/FROZEN/LARGEPROPS/SNOWTREEBASE2.BASE.1.DDS",
      ["FILE_DESTINATION"] = "CUSTOMTEXTURES/CODENAMEAWESOME/BIOMES/DEFROZEN/LARGEPROPS/"
    },
	{--FrozenLeaf
      ["EXTERNAL_FILE_SOURCE"] = ""..NMS_UNPACKED_DIR.."TEXTURES/PLANETS/BIOMES/FROZEN/MEDIUMPROPS/FROZENLEAF_1.BASE.DDS",
      ["FILE_DESTINATION"] = "CUSTOMTEXTURES/CODENAMEAWESOME/BIOMES/DEFROZEN/LARGEPROPS/"
    },
	{--MediumRock
      ["EXTERNAL_FILE_SOURCE"] = ""..NMS_UNPACKED_DIR.."TEXTURES/PLANETS/BIOMES/FROZEN/MEDIUMPROPS/MEDIUMROCK_1.DDS",
      ["FILE_DESTINATION"] = "CUSTOMTEXTURES/CODENAMEAWESOME/BIOMES/DEFROZEN/LARGEPROPS/"
    },
	{--Ice formation
      ["EXTERNAL_FILE_SOURCE"] = ""..NMS_UNPACKED_DIR.."TEXTURES/PLANETS/BIOMES/FROZEN/SMALLPROPS/ICEFORMATION.DDS",
      ["FILE_DESTINATION"] = "CUSTOMTEXTURES/CODENAMEAWESOME/BIOMES/DEFROZEN/LARGEPROPS/"
    },
	{--RockTiling
      ["EXTERNAL_FILE_SOURCE"] = ""..NMS_UNPACKED_DIR.."TEXTURES/PLANETS/BIOMES/FROZEN/LARGEPROPS/ROCKTILING.DDS",
      ["FILE_DESTINATION"] = "CUSTOMTEXTURES/CODENAMEAWESOME/BIOMES/DEFROZEN/LARGEPROPS/"
    },
  },
  ["MODIFICATIONS"] 		=
	{
		{
			["MBIN_CHANGE_TABLE"] =  {
				{--Create the models
					["MBIN_FILE_SOURCE"] = {--Use Notepad++ so you can collapse this section.
						{"MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGEROCKS.DESCRIPTOR.MBIN","CUSTOMMODELS\CODENAMEAWESOME\BIOMES\DEFROZEN\LARGEPROPS\LARGEROCKS.DESCRIPTOR.MBIN","REMOVE"},
						{"MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGEROCKS.GEOMETRY.DATA.MBIN.PC","CUSTOMMODELS\CODENAMEAWESOME\BIOMES\DEFROZEN\LARGEPROPS\LARGEROCKS.GEOMETRY.DATA.MBIN.PC","REMOVE"},
						{"MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGEROCKS.GEOMETRY.MBIN.PC","CUSTOMMODELS\CODENAMEAWESOME\BIOMES\DEFROZEN\LARGEPROPS\LARGEROCKS.GEOMETRY.MBIN.PC","REMOVE"},
						{"MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGEROCKS.SCENE.MBIN","CUSTOMMODELS\CODENAMEAWESOME\BIOMES\DEFROZEN\LARGEPROPS\LARGEROCKS.SCENE.MBIN","REMOVE"},
						{"MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE.ANIM.MBIN","CUSTOMMODELS\CODENAMEAWESOME\BIOMES\DEFROZEN\LARGEPROPS\LARGETREE.ANIM.MBIN","REMOVE"},
						{"MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE.DESCRIPTOR.MBIN","CUSTOMMODELS\CODENAMEAWESOME\BIOMES\DEFROZEN\LARGEPROPS\LARGETREE.DESCRIPTOR.MBIN","REMOVE"},
						{"MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE.GEOMETRY.DATA.MBIN.PC","CUSTOMMODELS\CODENAMEAWESOME\BIOMES\DEFROZEN\LARGEPROPS\LARGETREE.GEOMETRY.DATA.MBIN.PC","REMOVE"},
						{"MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE.GEOMETRY.MBIN.PC","CUSTOMMODELS\CODENAMEAWESOME\BIOMES\DEFROZEN\LARGEPROPS\LARGETREE.GEOMETRY.MBIN.PC","REMOVE"},
						{"MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE.SCENE.MBIN","CUSTOMMODELS\CODENAMEAWESOME\BIOMES\DEFROZEN\LARGEPROPS\LARGETREE.SCENE.MBIN","REMOVE"},
						{"MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREEBARE.DESCRIPTOR.MBIN","CUSTOMMODELS\CODENAMEAWESOME\BIOMES\DEFROZEN\LARGEPROPS\LARGETREEBARE.DESCRIPTOR.MBIN","REMOVE"},
						{"MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREEBARE.GEOMETRY.DATA.MBIN.PC","CUSTOMMODELS\CODENAMEAWESOME\BIOMES\DEFROZEN\LARGEPROPS\LARGETREEBARE.GEOMETRY.DATA.MBIN.PC","REMOVE"},
						{"MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREEBARE.GEOMETRY.MBIN.PC","CUSTOMMODELS\CODENAMEAWESOME\BIOMES\DEFROZEN\LARGEPROPS\LARGETREEBARE.GEOMETRY.MBIN.PC","REMOVE"},
						{"MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREEBARE.SCENE.MBIN","CUSTOMMODELS\CODENAMEAWESOME\BIOMES\DEFROZEN\LARGEPROPS\LARGETREEBARE.SCENE.MBIN","REMOVE"},
						{"MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGEROCKS\FROZENLARGETREE_MAT.MATERIAL.MBIN","CUSTOMMODELS\CODENAMEAWESOME\BIOMES\DEFROZEN\LARGEPROPS\LARGEROCKS\FROZENLARGETREE_MAT.MATERIAL.MBIN","REMOVE"},
						{"MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGEROCKS\FROZENLEAF1_MAT.MATERIAL.MBIN","CUSTOMMODELS\CODENAMEAWESOME\BIOMES\DEFROZEN\LARGEPROPS\LARGEROCKS\FROZENLEAF1_MAT.MATERIAL.MBIN","REMOVE"},
						{"MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGEROCKS\ICE_MAT.MATERIAL.MBIN","CUSTOMMODELS\CODENAMEAWESOME\BIOMES\DEFROZEN\LARGEPROPS\LARGEROCKS\ICE_MAT.MATERIAL.MBIN","REMOVE"},
						{"MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGEROCKS\IMPOSTER_IMPOSTERMAT.MATERIAL.MBIN","CUSTOMMODELS\CODENAMEAWESOME\BIOMES\DEFROZEN\LARGEPROPS\LARGEROCKS\IMPOSTER_IMPOSTERMAT.MATERIAL.MBIN","REMOVE"},
						{"MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGEROCKS\LAMBERT1.MATERIAL.MBIN","CUSTOMMODELS\CODENAMEAWESOME\BIOMES\DEFROZEN\LARGEPROPS\LARGEROCKS\LAMBERT1.MATERIAL.MBIN","REMOVE"},
						{"MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGEROCKS\LARGETILINGROCK_A.MATERIAL.MBIN","CUSTOMMODELS\CODENAMEAWESOME\BIOMES\DEFROZEN\LARGEPROPS\LARGEROCKS\LARGETILINGROCK_A.MATERIAL.MBIN","REMOVE"},
						{"MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGEROCKS\MEDIUMPLANT_FROZENLARGETREE_MAT1.MATERIAL.MBIN","CUSTOMMODELS\CODENAMEAWESOME\BIOMES\DEFROZEN\LARGEPROPS\LARGEROCKS\MEDIUMPLANT_FROZENLARGETREE_MAT1.MATERIAL.MBIN","REMOVE"},
						{"MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGEROCKS\SMALLPLANT_FROZENLEAF1_MAT.MATERIAL.MBIN","CUSTOMMODELS\CODENAMEAWESOME\BIOMES\DEFROZEN\LARGEPROPS\LARGEROCKS\SMALLPLANT_FROZENLEAF1_MAT.MATERIAL.MBIN","REMOVE"},
						{"MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGEROCKS\SMOOTHROCKTILING_MAT.MATERIAL.MBIN","CUSTOMMODELS\CODENAMEAWESOME\BIOMES\DEFROZEN\LARGEPROPS\LARGEROCKS\SMOOTHROCKTILING_MAT.MATERIAL.MBIN","REMOVE"},
						{"MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\BARK.MATERIAL.MBIN","CUSTOMMODELS\CODENAMEAWESOME\BIOMES\DEFROZEN\LARGEPROPS\LARGETREE\BARK.MATERIAL.MBIN","REMOVE"},
						{"MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\BARK1.MATERIAL.MBIN","CUSTOMMODELS\CODENAMEAWESOME\BIOMES\DEFROZEN\LARGEPROPS\LARGETREE\BARK1.MATERIAL.MBIN","REMOVE"},
						{"MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\BILLBOADLEAVES_NEWLEAFMAT.MATERIAL.MBIN","CUSTOMMODELS\CODENAMEAWESOME\BIOMES\DEFROZEN\LARGEPROPS\LARGETREE\BILLBOADLEAVES_NEWLEAFMAT.MATERIAL.MBIN","REMOVE"},
						{"MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\FROZENFRONDMAT.MATERIAL.MBIN","CUSTOMMODELS\CODENAMEAWESOME\BIOMES\DEFROZEN\LARGEPROPS\LARGETREE\FROZENFRONDMAT.MATERIAL.MBIN","REMOVE"},
						{"MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\FROZENLARGETREE_MAT.MATERIAL.MBIN","CUSTOMMODELS\CODENAMEAWESOME\BIOMES\DEFROZEN\LARGEPROPS\LARGETREE\FROZENLARGETREE_MAT.MATERIAL.MBIN","REMOVE"},
						{"MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\IMPOSTERMAT.MATERIAL.MBIN","CUSTOMMODELS\CODENAMEAWESOME\BIOMES\DEFROZEN\LARGEPROPS\LARGETREE\IMPOSTERMAT.MATERIAL.MBIN","REMOVE"},
						{"MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\LAMBERT1.MATERIAL.MBIN","CUSTOMMODELS\CODENAMEAWESOME\BIOMES\DEFROZEN\LARGEPROPS\LARGETREE\LAMBERT1.MATERIAL.MBIN","REMOVE"},
						{"MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREE\SNOWTILING_MAT.MATERIAL.MBIN","CUSTOMMODELS\CODENAMEAWESOME\BIOMES\DEFROZEN\LARGEPROPS\LARGETREE\SNOWTILING_MAT.MATERIAL.MBIN","REMOVE"},
						{"MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREEBARE\FROZENLARGETREE_MAT.MATERIAL.MBIN","CUSTOMMODELS\CODENAMEAWESOME\BIOMES\DEFROZEN\LARGEPROPS\LARGETREEBARE\FROZENLARGETREE_MAT.MATERIAL.MBIN","REMOVE"},
						{"MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREEBARE\HANGINGICE_MAT.MATERIAL.MBIN","CUSTOMMODELS\CODENAMEAWESOME\BIOMES\DEFROZEN\LARGEPROPS\LARGETREEBARE\HANGINGICE_MAT.MATERIAL.MBIN","REMOVE"},
						{"MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREEBARE\HANGINGICESOLID_MAT.MATERIAL.MBIN","CUSTOMMODELS\CODENAMEAWESOME\BIOMES\DEFROZEN\LARGEPROPS\LARGETREEBARE\HANGINGICESOLID_MAT.MATERIAL.MBIN","REMOVE"},
						{"MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREEBARE\IMPOSTERMAT.MATERIAL.MBIN","CUSTOMMODELS\CODENAMEAWESOME\BIOMES\DEFROZEN\LARGEPROPS\LARGETREEBARE\IMPOSTERMAT.MATERIAL.MBIN","REMOVE"},
						{"MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREEBARE\LAMBERT1.MATERIAL.MBIN","CUSTOMMODELS\CODENAMEAWESOME\BIOMES\DEFROZEN\LARGEPROPS\LARGETREEBARE\LAMBERT1.MATERIAL.MBIN","REMOVE"},
						{"MODELS\PLANETS\BIOMES\FROZEN\LARGEPROPS\LARGETREEBARE\SNOWTILING_MAT.MATERIAL.MBIN","CUSTOMMODELS\CODENAMEAWESOME\BIOMES\DEFROZEN\LARGEPROPS\LARGETREEBARE\SNOWTILING_MAT.MATERIAL.MBIN","REMOVE"},
						{"MODELS\PLANETS\BIOMES\FROZEN\MEDIUMPROPS\MEDIUMICEDRIFTS.DESCRIPTOR.MBIN","CUSTOMMODELS\CODENAMEAWESOME\BIOMES\DEFROZEN\MEDIUMPROPS\MEDIUMICEDRIFTS.DESCRIPTOR.MBIN","REMOVE"},
						{"MODELS\PLANETS\BIOMES\FROZEN\MEDIUMPROPS\MEDIUMICEDRIFTS.GEOMETRY.DATA.MBIN.PC","CUSTOMMODELS\CODENAMEAWESOME\BIOMES\DEFROZEN\MEDIUMPROPS\MEDIUMICEDRIFTS.GEOMETRY.DATA.MBIN.PC","REMOVE"},
						{"MODELS\PLANETS\BIOMES\FROZEN\MEDIUMPROPS\MEDIUMICEDRIFTS.GEOMETRY.MBIN.PC","CUSTOMMODELS\CODENAMEAWESOME\BIOMES\DEFROZEN\MEDIUMPROPS\MEDIUMICEDRIFTS.GEOMETRY.MBIN.PC","REMOVE"},
						{"MODELS\PLANETS\BIOMES\FROZEN\MEDIUMPROPS\MEDIUMICEDRIFTS.SCENE.MBIN","CUSTOMMODELS\CODENAMEAWESOME\BIOMES\DEFROZEN\MEDIUMPROPS\MEDIUMICEDRIFTS.SCENE.MBIN","REMOVE"},
						{"MODELS\PLANETS\BIOMES\FROZEN\MEDIUMPROPS\MEDIUMPLANT.DESCRIPTOR.MBIN","CUSTOMMODELS\CODENAMEAWESOME\BIOMES\DEFROZEN\MEDIUMPROPS\MEDIUMPLANT.DESCRIPTOR.MBIN","REMOVE"},
						{"MODELS\PLANETS\BIOMES\FROZEN\MEDIUMPROPS\MEDIUMPLANT.GEOMETRY.DATA.MBIN.PC","CUSTOMMODELS\CODENAMEAWESOME\BIOMES\DEFROZEN\MEDIUMPROPS\MEDIUMPLANT.GEOMETRY.DATA.MBIN.PC","REMOVE"},
						{"MODELS\PLANETS\BIOMES\FROZEN\MEDIUMPROPS\MEDIUMPLANT.GEOMETRY.MBIN.PC","CUSTOMMODELS\CODENAMEAWESOME\BIOMES\DEFROZEN\MEDIUMPROPS\MEDIUMPLANT.GEOMETRY.MBIN.PC","REMOVE"},
						{"MODELS\PLANETS\BIOMES\FROZEN\MEDIUMPROPS\MEDIUMPLANT.SCENE.MBIN","CUSTOMMODELS\CODENAMEAWESOME\BIOMES\DEFROZEN\MEDIUMPROPS\MEDIUMPLANT.SCENE.MBIN","REMOVE"},
						{"MODELS\PLANETS\BIOMES\FROZEN\MEDIUMPROPS\MEDIUMROCK.DESCRIPTOR.MBIN","CUSTOMMODELS\CODENAMEAWESOME\BIOMES\DEFROZEN\MEDIUMPROPS\MEDIUMROCK.DESCRIPTOR.MBIN","REMOVE"},
						{"MODELS\PLANETS\BIOMES\FROZEN\MEDIUMPROPS\MEDIUMROCK.GEOMETRY.DATA.MBIN.PC","CUSTOMMODELS\CODENAMEAWESOME\BIOMES\DEFROZEN\MEDIUMPROPS\MEDIUMROCK.GEOMETRY.DATA.MBIN.PC","REMOVE"},
						{"MODELS\PLANETS\BIOMES\FROZEN\MEDIUMPROPS\MEDIUMROCK.GEOMETRY.MBIN.PC","CUSTOMMODELS\CODENAMEAWESOME\BIOMES\DEFROZEN\MEDIUMPROPS\MEDIUMROCK.GEOMETRY.MBIN.PC","REMOVE"},
						{"MODELS\PLANETS\BIOMES\FROZEN\MEDIUMPROPS\MEDIUMROCK.SCENE.MBIN","CUSTOMMODELS\CODENAMEAWESOME\BIOMES\DEFROZEN\MEDIUMPROPS\MEDIUMROCK.SCENE.MBIN","REMOVE"},
						{"MODELS\PLANETS\BIOMES\FROZEN\MEDIUMPROPS\MEDIUMICEDRIFTS\ICE_MAT.MATERIAL.MBIN","CUSTOMMODELS\CODENAMEAWESOME\BIOMES\DEFROZEN\MEDIUMPROPS\MEDIUMICEDRIFTS\ICE_MAT.MATERIAL.MBIN","REMOVE"},
						{"MODELS\PLANETS\BIOMES\FROZEN\MEDIUMPROPS\MEDIUMICEDRIFTS\SNOWTILING_MAT.MATERIAL.MBIN","CUSTOMMODELS\CODENAMEAWESOME\BIOMES\DEFROZEN\MEDIUMPROPS\MEDIUMICEDRIFTS\SNOWTILING_MAT.MATERIAL.MBIN","REMOVE"},
						{"MODELS\PLANETS\BIOMES\FROZEN\MEDIUMPROPS\MEDIUMPLANT\BARK2.MATERIAL.MBIN","CUSTOMMODELS\CODENAMEAWESOME\BIOMES\DEFROZEN\MEDIUMPROPS\MEDIUMPLANT\BARK2.MATERIAL.MBIN","REMOVE"},
						{"MODELS\PLANETS\BIOMES\FROZEN\MEDIUMPROPS\MEDIUMPLANT\FROND2.MATERIAL.MBIN","CUSTOMMODELS\CODENAMEAWESOME\BIOMES\DEFROZEN\MEDIUMPROPS\MEDIUMPLANT\FROND2.MATERIAL.MBIN","REMOVE"},
						{"MODELS\PLANETS\BIOMES\FROZEN\MEDIUMPROPS\MEDIUMPLANT\FROZENLARGETREE_MAT.MATERIAL.MBIN","CUSTOMMODELS\CODENAMEAWESOME\BIOMES\DEFROZEN\MEDIUMPROPS\MEDIUMPLANT\FROZENLARGETREE_MAT.MATERIAL.MBIN","REMOVE"},
						{"MODELS\PLANETS\BIOMES\FROZEN\MEDIUMPROPS\MEDIUMPLANT\FROZENLEAF1_MAT.MATERIAL.MBIN","CUSTOMMODELS\CODENAMEAWESOME\BIOMES\DEFROZEN\MEDIUMPROPS\MEDIUMPLANT\FROZENLEAF1_MAT.MATERIAL.MBIN","REMOVE"},
						{"MODELS\PLANETS\BIOMES\FROZEN\MEDIUMPROPS\MEDIUMPLANT\IMPOSTERMAT.MATERIAL.MBIN","CUSTOMMODELS\CODENAMEAWESOME\BIOMES\DEFROZEN\MEDIUMPROPS\MEDIUMPLANT\IMPOSTERMAT.MATERIAL.MBIN","REMOVE"},
						{"MODELS\PLANETS\BIOMES\FROZEN\MEDIUMPROPS\MEDIUMPLANT\LAMBERT1.MATERIAL.MBIN","CUSTOMMODELS\CODENAMEAWESOME\BIOMES\DEFROZEN\MEDIUMPROPS\MEDIUMPLANT\LAMBERT1.MATERIAL.MBIN","REMOVE"},
						{"MODELS\PLANETS\BIOMES\FROZEN\MEDIUMPROPS\MEDIUMROCK\FLATROCKS_SNOWTILING_MAT.MATERIAL.MBIN","CUSTOMMODELS\CODENAMEAWESOME\BIOMES\DEFROZEN\MEDIUMPROPS\MEDIUMROCK\FLATROCKS_SNOWTILING_MAT.MATERIAL.MBIN","REMOVE"},
						{"MODELS\PLANETS\BIOMES\FROZEN\MEDIUMPROPS\MEDIUMROCK\FROZENLARGETREE_MAT.MATERIAL.MBIN","CUSTOMMODELS\CODENAMEAWESOME\BIOMES\DEFROZEN\MEDIUMPROPS\MEDIUMROCK\FROZENLARGETREE_MAT.MATERIAL.MBIN","REMOVE"},
						{"MODELS\PLANETS\BIOMES\FROZEN\MEDIUMPROPS\MEDIUMROCK\FROZENLEAF1_MAT.MATERIAL.MBIN","CUSTOMMODELS\CODENAMEAWESOME\BIOMES\DEFROZEN\MEDIUMPROPS\MEDIUMROCK\FROZENLEAF1_MAT.MATERIAL.MBIN","REMOVE"},
						{"MODELS\PLANETS\BIOMES\FROZEN\MEDIUMPROPS\MEDIUMROCK\FROZENMEDROCK_MAT.MATERIAL.MBIN","CUSTOMMODELS\CODENAMEAWESOME\BIOMES\DEFROZEN\MEDIUMPROPS\MEDIUMROCK\FROZENMEDROCK_MAT.MATERIAL.MBIN","REMOVE"},
						{"MODELS\PLANETS\BIOMES\FROZEN\MEDIUMPROPS\MEDIUMROCK\LAMBERT1.MATERIAL.MBIN","CUSTOMMODELS\CODENAMEAWESOME\BIOMES\DEFROZEN\MEDIUMPROPS\MEDIUMROCK\LAMBERT1.MATERIAL.MBIN","REMOVE"},
						{"MODELS\PLANETS\BIOMES\FROZEN\MEDIUMPROPS\MEDIUMROCK\LARGEROCKS_FROZENLEAF1_MAT.MATERIAL.MBIN","CUSTOMMODELS\CODENAMEAWESOME\BIOMES\DEFROZEN\MEDIUMPROPS\MEDIUMROCK\LARGEROCKS_FROZENLEAF1_MAT.MATERIAL.MBIN","REMOVE"},
						{"MODELS\PLANETS\BIOMES\FROZEN\MEDIUMPROPS\MEDIUMROCK\ROCKTEMPLATWE_SMOOTHROCKTILING_MAT.MATERIAL.MBIN","CUSTOMMODELS\CODENAMEAWESOME\BIOMES\DEFROZEN\MEDIUMPROPS\MEDIUMROCK\ROCKTEMPLATWE_SMOOTHROCKTILING_MAT.MATERIAL.MBIN","REMOVE"},
						{"MODELS\PLANETS\BIOMES\FROZEN\MEDIUMPROPS\MEDIUMROCK\TILINGROCKFROZEN_MAT.MATERIAL.MBIN","CUSTOMMODELS\CODENAMEAWESOME\BIOMES\DEFROZEN\MEDIUMPROPS\MEDIUMROCK\TILINGROCKFROZEN_MAT.MATERIAL.MBIN","REMOVE"},
						{"MODELS\PLANETS\BIOMES\FROZEN\SMALLPROPS\SMALLICEFORMATION.DESCRIPTOR.MBIN","CUSTOMMODELS\CODENAMEAWESOME\BIOMES\DEFROZEN\SMALLPROPS\SMALLICEFORMATION.DESCRIPTOR.MBIN","REMOVE"},
						{"MODELS\PLANETS\BIOMES\FROZEN\SMALLPROPS\SMALLICEFORMATION.GEOMETRY.DATA.MBIN.PC","CUSTOMMODELS\CODENAMEAWESOME\BIOMES\DEFROZEN\SMALLPROPS\SMALLICEFORMATION.GEOMETRY.DATA.MBIN.PC","REMOVE"},
						{"MODELS\PLANETS\BIOMES\FROZEN\SMALLPROPS\SMALLICEFORMATION.GEOMETRY.MBIN.PC","CUSTOMMODELS\CODENAMEAWESOME\BIOMES\DEFROZEN\SMALLPROPS\SMALLICEFORMATION.GEOMETRY.MBIN.PC","REMOVE"},
						{"MODELS\PLANETS\BIOMES\FROZEN\SMALLPROPS\SMALLICEFORMATION.SCENE.MBIN","CUSTOMMODELS\CODENAMEAWESOME\BIOMES\DEFROZEN\SMALLPROPS\SMALLICEFORMATION.SCENE.MBIN","REMOVE"},
						{"MODELS\PLANETS\BIOMES\FROZEN\SMALLPROPS\SMALLPLANT.DESCRIPTOR.MBIN","CUSTOMMODELS\CODENAMEAWESOME\BIOMES\DEFROZEN\SMALLPROPS\SMALLPLANT.DESCRIPTOR.MBIN","REMOVE"},
						{"MODELS\PLANETS\BIOMES\FROZEN\SMALLPROPS\SMALLPLANT.GEOMETRY.DATA.MBIN.PC","CUSTOMMODELS\CODENAMEAWESOME\BIOMES\DEFROZEN\SMALLPROPS\SMALLPLANT.GEOMETRY.DATA.MBIN.PC","REMOVE"},
						{"MODELS\PLANETS\BIOMES\FROZEN\SMALLPROPS\SMALLPLANT.GEOMETRY.MBIN.PC","CUSTOMMODELS\CODENAMEAWESOME\BIOMES\DEFROZEN\SMALLPROPS\SMALLPLANT.GEOMETRY.MBIN.PC","REMOVE"},
						{"MODELS\PLANETS\BIOMES\FROZEN\SMALLPROPS\SMALLPLANT.SCENE.MBIN","CUSTOMMODELS\CODENAMEAWESOME\BIOMES\DEFROZEN\SMALLPROPS\SMALLPLANT.SCENE.MBIN","REMOVE"},
						{"MODELS\PLANETS\BIOMES\FROZEN\SMALLPROPS\SMALLROCKS.DESCRIPTOR.MBIN","CUSTOMMODELS\CODENAMEAWESOME\BIOMES\DEFROZEN\SMALLPROPS\SMALLROCKS.DESCRIPTOR.MBIN","REMOVE"},
						{"MODELS\PLANETS\BIOMES\FROZEN\SMALLPROPS\SMALLROCKS.GEOMETRY.DATA.MBIN.PC","CUSTOMMODELS\CODENAMEAWESOME\BIOMES\DEFROZEN\SMALLPROPS\SMALLROCKS.GEOMETRY.DATA.MBIN.PC","REMOVE"},
						{"MODELS\PLANETS\BIOMES\FROZEN\SMALLPROPS\SMALLROCKS.GEOMETRY.MBIN.PC","CUSTOMMODELS\CODENAMEAWESOME\BIOMES\DEFROZEN\SMALLPROPS\SMALLROCKS.GEOMETRY.MBIN.PC","REMOVE"},
						{"MODELS\PLANETS\BIOMES\FROZEN\SMALLPROPS\SMALLROCKS.SCENE.MBIN","CUSTOMMODELS\CODENAMEAWESOME\BIOMES\DEFROZEN\SMALLPROPS\SMALLROCKS.SCENE.MBIN","REMOVE"},
						{"MODELS\PLANETS\BIOMES\FROZEN\SMALLPROPS\SMALLROCKSSHARDS.DESCRIPTOR.MBIN","CUSTOMMODELS\CODENAMEAWESOME\BIOMES\DEFROZEN\SMALLPROPS\SMALLROCKSSHARDS.DESCRIPTOR.MBIN","REMOVE"},
						{"MODELS\PLANETS\BIOMES\FROZEN\SMALLPROPS\SMALLROCKSSHARDS.GEOMETRY.DATA.MBIN.PC","CUSTOMMODELS\CODENAMEAWESOME\BIOMES\DEFROZEN\SMALLPROPS\SMALLROCKSSHARDS.GEOMETRY.DATA.MBIN.PC","REMOVE"},
						{"MODELS\PLANETS\BIOMES\FROZEN\SMALLPROPS\SMALLROCKSSHARDS.GEOMETRY.MBIN.PC","CUSTOMMODELS\CODENAMEAWESOME\BIOMES\DEFROZEN\SMALLPROPS\SMALLROCKSSHARDS.GEOMETRY.MBIN.PC","REMOVE"},
						{"MODELS\PLANETS\BIOMES\FROZEN\SMALLPROPS\SMALLROCKSSHARDS.SCENE.MBIN","CUSTOMMODELS\CODENAMEAWESOME\BIOMES\DEFROZEN\SMALLPROPS\SMALLROCKSSHARDS.SCENE.MBIN","REMOVE"},
						{"MODELS\PLANETS\BIOMES\FROZEN\SMALLPROPS\SNOWFRAGMENTS.DESCRIPTOR.MBIN","CUSTOMMODELS\CODENAMEAWESOME\BIOMES\DEFROZEN\SMALLPROPS\SNOWFRAGMENTS.DESCRIPTOR.MBIN","REMOVE"},
						{"MODELS\PLANETS\BIOMES\FROZEN\SMALLPROPS\SNOWFRAGMENTS.GEOMETRY.DATA.MBIN.PC","CUSTOMMODELS\CODENAMEAWESOME\BIOMES\DEFROZEN\SMALLPROPS\SNOWFRAGMENTS.GEOMETRY.DATA.MBIN.PC","REMOVE"},
						{"MODELS\PLANETS\BIOMES\FROZEN\SMALLPROPS\SNOWFRAGMENTS.GEOMETRY.MBIN.PC","CUSTOMMODELS\CODENAMEAWESOME\BIOMES\DEFROZEN\SMALLPROPS\SNOWFRAGMENTS.GEOMETRY.MBIN.PC","REMOVE"},
						{"MODELS\PLANETS\BIOMES\FROZEN\SMALLPROPS\SNOWFRAGMENTS.SCENE.MBIN","CUSTOMMODELS\CODENAMEAWESOME\BIOMES\DEFROZEN\SMALLPROPS\SNOWFRAGMENTS.SCENE.MBIN","REMOVE"},
						{"MODELS\PLANETS\BIOMES\FROZEN\SMALLPROPS\SMALLICEFORMATION\ICEFORMATION_MAT.MATERIAL.MBIN","CUSTOMMODELS\CODENAMEAWESOME\BIOMES\DEFROZEN\SMALLPROPS\SMALLICEFORMATION\ICEFORMATION_MAT.MATERIAL.MBIN","REMOVE"},
						{"MODELS\PLANETS\BIOMES\FROZEN\SMALLPROPS\SMALLPLANT\FLOWERHEAD_MAT.MATERIAL.MBIN","CUSTOMMODELS\CODENAMEAWESOME\BIOMES\DEFROZEN\SMALLPROPS\SMALLPLANT\FLOWERHEAD_MAT.MATERIAL.MBIN","REMOVE"},
						{"MODELS\PLANETS\BIOMES\FROZEN\SMALLPROPS\SMALLPLANT\FROZENLEAF1_MAT.MATERIAL.MBIN","CUSTOMMODELS\CODENAMEAWESOME\BIOMES\DEFROZEN\SMALLPROPS\SMALLPLANT\FROZENLEAF1_MAT.MATERIAL.MBIN","REMOVE"},
						{"MODELS\PLANETS\BIOMES\FROZEN\SMALLPROPS\SMALLPLANT\LAMBERT1.MATERIAL.MBIN","CUSTOMMODELS\CODENAMEAWESOME\BIOMES\DEFROZEN\SMALLPROPS\SMALLPLANT\LAMBERT1.MATERIAL.MBIN","REMOVE"},
						{"MODELS\PLANETS\BIOMES\FROZEN\SMALLPROPS\SMALLPLANT\LEAVES_MAT.MATERIAL.MBIN","CUSTOMMODELS\CODENAMEAWESOME\BIOMES\DEFROZEN\SMALLPROPS\SMALLPLANT\LEAVES_MAT.MATERIAL.MBIN","REMOVE"},
						{"MODELS\PLANETS\BIOMES\FROZEN\SMALLPROPS\SMALLPLANT\LEAVESB_MAT.MATERIAL.MBIN","CUSTOMMODELS\CODENAMEAWESOME\BIOMES\DEFROZEN\SMALLPROPS\SMALLPLANT\LEAVESB_MAT.MATERIAL.MBIN","REMOVE"},
						{"MODELS\PLANETS\BIOMES\FROZEN\SMALLPROPS\SMALLPLANT\MEDIUMPLANT_FROZENLARGETREE_MAT2.MATERIAL.MBIN","CUSTOMMODELS\CODENAMEAWESOME\BIOMES\DEFROZEN\SMALLPROPS\SMALLPLANT\MEDIUMPLANT_FROZENLARGETREE_MAT2.MATERIAL.MBIN","REMOVE"},
						{"MODELS\PLANETS\BIOMES\FROZEN\SMALLPROPS\SMALLROCKS\ICE_MAT.MATERIAL.MBIN","CUSTOMMODELS\CODENAMEAWESOME\BIOMES\DEFROZEN\SMALLPROPS\SMALLROCKS\ICE_MAT.MATERIAL.MBIN","REMOVE"},
						{"MODELS\PLANETS\BIOMES\FROZEN\SMALLPROPS\SMALLROCKS\LAMBERT1.MATERIAL.MBIN","CUSTOMMODELS\CODENAMEAWESOME\BIOMES\DEFROZEN\SMALLPROPS\SMALLROCKS\LAMBERT1.MATERIAL.MBIN","REMOVE"},
						{"MODELS\PLANETS\BIOMES\FROZEN\SMALLPROPS\SMALLROCKS\ROCKBASE_MAT.MATERIAL.MBIN","CUSTOMMODELS\CODENAMEAWESOME\BIOMES\DEFROZEN\SMALLPROPS\SMALLROCKS\ROCKBASE_MAT.MATERIAL.MBIN","REMOVE"},
						{"MODELS\PLANETS\BIOMES\FROZEN\SMALLPROPS\SMALLROCKS\SNOWTILING_MAT.MATERIAL.MBIN","CUSTOMMODELS\CODENAMEAWESOME\BIOMES\DEFROZEN\SMALLPROPS\SMALLROCKS\SNOWTILING_MAT.MATERIAL.MBIN","REMOVE"},
						{"MODELS\PLANETS\BIOMES\FROZEN\SMALLPROPS\SMALLROCKS\TILINGROCKFROZEN_MAT.MATERIAL.MBIN","CUSTOMMODELS\CODENAMEAWESOME\BIOMES\DEFROZEN\SMALLPROPS\SMALLROCKS\TILINGROCKFROZEN_MAT.MATERIAL.MBIN","REMOVE"},
						{"MODELS\PLANETS\BIOMES\FROZEN\SMALLPROPS\SMALLROCKSSHARDS\SMALLROCKBASE_MAT.MATERIAL.MBIN","CUSTOMMODELS\CODENAMEAWESOME\BIOMES\DEFROZEN\SMALLPROPS\SMALLROCKSSHARDS\SMALLROCKBASE_MAT.MATERIAL.MBIN","REMOVE"},
						{"MODELS\PLANETS\BIOMES\FROZEN\SMALLPROPS\SMALLROCKSSHARDS\SMALLROCKS_SNOWTILING_MAT.MATERIAL.MBIN","CUSTOMMODELS\CODENAMEAWESOME\BIOMES\DEFROZEN\SMALLPROPS\SMALLROCKSSHARDS\SMALLROCKS_SNOWTILING_MAT.MATERIAL.MBIN","REMOVE"},
						{"MODELS\PLANETS\BIOMES\FROZEN\SMALLPROPS\SMALLROCKSSHARDS\SNOWTILING_MAT.MATERIAL.MBIN","CUSTOMMODELS\CODENAMEAWESOME\BIOMES\DEFROZEN\SMALLPROPS\SMALLROCKSSHARDS\SNOWTILING_MAT.MATERIAL.MBIN","REMOVE"},
						{"MODELS\PLANETS\BIOMES\FROZEN\SMALLPROPS\SNOWFRAGMENTS\TINYSLATEMAT.MATERIAL.MBIN","CUSTOMMODELS\CODENAMEAWESOME\BIOMES\DEFROZEN\SMALLPROPS\SNOWFRAGMENTS\TINYSLATEMAT.MATERIAL.MBIN","REMOVE"},
					}
				},
				{--Replace the material paths in all the scenes.
					["MBIN_FILE_SOURCE"] = {
						"CUSTOMMODELS/CODENAMEAWESOME/BIOMES/DEFROZEN/LARGEPROPS/LARGEROCKS.SCENE.MBIN",
						"CUSTOMMODELS/CODENAMEAWESOME/BIOMES/DEFROZEN/LARGEPROPS/LARGETREE.SCENE.MBIN",
						"CUSTOMMODELS/CODENAMEAWESOME/BIOMES/DEFROZEN/LARGEPROPS/LARGETREEBARE.SCENE.MBIN",
						"CUSTOMMODELS/CODENAMEAWESOME/BIOMES/DEFROZEN/MEDIUMPROPS/MEDIUMICEDRIFTS.SCENE.MBIN",
						"CUSTOMMODELS/CODENAMEAWESOME/BIOMES/DEFROZEN/MEDIUMPROPS/MEDIUMPLANT.SCENE.MBIN",
						"CUSTOMMODELS/CODENAMEAWESOME/BIOMES/DEFROZEN/MEDIUMPROPS/MEDIUMROCK.SCENE.MBIN",
						"CUSTOMMODELS/CODENAMEAWESOME/BIOMES/DEFROZEN/SMALLPROPS/SMALLICEFORMATION.SCENE.MBIN",
						"CUSTOMMODELS/CODENAMEAWESOME/BIOMES/DEFROZEN/SMALLPROPS/SMALLPLANT.SCENE.MBIN",
						"CUSTOMMODELS/CODENAMEAWESOME/BIOMES/DEFROZEN/SMALLPROPS/SMALLROCKS.SCENE.MBIN",
						"CUSTOMMODELS/CODENAMEAWESOME/BIOMES/DEFROZEN/SMALLPROPS/SMALLROCKSSHARDS.SCENE.MBIN",
						"CUSTOMMODELS/CODENAMEAWESOME/BIOMES/DEFROZEN/SMALLPROPS/SNOWFRAGMENTS.SCENE.MBIN",

					},
					["EXML_CHANGE_TABLE"] = {
						{
							["SPECIAL_KEY_WORDS"] = {"Name","MATERIAL"},
							["REPLACE_TYPE"] = "RAW",
							["VALUE_CHANGE_TABLE"] = {
								{[[MODELS\PLANETS\BIOMES\FROZEN\]],[[CUSTOMMODELS\CODENAMEAWESOME\BIOMES\DEFROZEN\]]},
							}
						}
					}
				},
				{--Copy some texture MBINs
					["MBIN_FILE_SOURCE"] = {
						{"TEXTURES/PLANETS/BIOMES/FROZEN/LARGEPROPS/TILINGROCKA.TEXTURE.MBIN","CUSTOMTEXTURES/CODENAMEAWESOME/BIOMES/DEFROZEN/LARGEPROPS/TILINGROCKA.TEXTURE.MBIN","REMOVE"},
						{"TEXTURES/PLANETS/BIOMES/FROZEN/LARGEPROPS/ROCKTILING.TEXTURE.MBIN","CUSTOMTEXTURES/CODENAMEAWESOME/BIOMES/DEFROZEN/LARGEPROPS/ROCKTILING.TEXTURE.MBIN","REMOVE"},
						{"TEXTURES/PLANETS/BIOMES/FROZEN/LARGEPROPS/SMOOTHROCKTILING.TEXTURE.MBIN","CUSTOMTEXTURES/CODENAMEAWESOME/BIOMES/DEFROZEN/LARGEPROPS/SMOOTHROCKTILING.TEXTURE.MBIN","REMOVE"},
						{"TEXTURES/PLANETS/BIOMES/FROZEN/LARGEPROPS/SNOWFROND.TEXTURE.MBIN","CUSTOMTEXTURES/CODENAMEAWESOME/BIOMES/DEFROZEN/LARGEPROPS/SNOWFROND.TEXTURE.MBIN","REMOVE"},
						{"TEXTURES/PLANETS/BIOMES/FROZEN/LARGEPROPS/SNOWTREEBASE2.TEXTURE.MBIN","CUSTOMTEXTURES/CODENAMEAWESOME/BIOMES/DEFROZEN/LARGEPROPS/SNOWTREEBASE2.TEXTURE.MBIN","REMOVE"},
						{"TEXTURES/PLANETS/BIOMES/FROZEN/LARGEPROPS/SNOWBILLLEAF.TEXTURE.MBIN","CUSTOMTEXTURES/CODENAMEAWESOME/BIOMES/DEFROZEN/LARGEPROPS/SNOWBILLLEAF.TEXTURE.MBIN","REMOVE"},
						{"TEXTURES/PLANETS/BIOMES/FROZEN/LARGEPROPS/TREEBASE.TEXTURE.MBIN","CUSTOMTEXTURES/CODENAMEAWESOME/BIOMES/DEFROZEN/LARGEPROPS/TREEBASE.TEXTURE.MBIN","REMOVE"},
						{"TEXTURES/PLANETS/BIOMES/FROZEN/MEDIUMPROPS/FROZENLEAF_1.TEXTURE.MBIN","CUSTOMTEXTURES/CODENAMEAWESOME/BIOMES/DEFROZEN/MEDIUMPROPS/FROZENLEAF_1.TEXTURE.MBIN","REMOVE"},
						{"TEXTURES/PLANETS/BIOMES/FROZEN/MEDIUMPROPS/MEDIUMROCK_1.TEXTURE.MBIN","CUSTOMTEXTURES/CODENAMEAWESOME/BIOMES/DEFROZEN/MEDIUMPROPS/MEDIUMROCK_1.TEXTURE.MBIN","REMOVE"},
						{"TEXTURES/PLANETS/BIOMES/FROZEN/SMALLPROPS/ICEFORMATION.TEXTURE.MBIN","CUSTOMTEXTURES/CODENAMEAWESOME/BIOMES/DEFROZEN/SMALLPROPS/ICEFORMATION.TEXTURE.MBIN","REMOVE"},
					}
				},
				{--Remove snow OVERLAY from texture MBINs that have them
					["MBIN_FILE_SOURCE"] = {
						"CUSTOMTEXTURES/CODENAMEAWESOME/BIOMES/DEFROZEN/LARGEPROPS/SNOWFROND.TEXTURE.MBIN",
						"CUSTOMTEXTURES/CODENAMEAWESOME/BIOMES/DEFROZEN/LARGEPROPS/SNOWBILLLEAF.TEXTURE.MBIN",
						"CUSTOMTEXTURES/CODENAMEAWESOME/BIOMES/DEFROZEN/LARGEPROPS/TILINGROCKA.TEXTURE.MBIN",
					},
					["EXML_CHANGE_TABLE"] = {
						{
							["SPECIAL_KEY_WORDS"] = {"Name","OVERLAY"},
							["VALUE_CHANGE_TABLE"] = {
								{"Probability",0}
							}
						}
					}
				},
				{--Remove SNOW layer from texture MBINs that have them
					["MBIN_FILE_SOURCE"] = {
						"CUSTOMTEXTURES/CODENAMEAWESOME/BIOMES/DEFROZEN/LARGEPROPS/TREEBASE.TEXTURE.MBIN",
						"CUSTOMTEXTURES/CODENAMEAWESOME/BIOMES/DEFROZEN/MEDIUMPROPS/MEDIUMROCK_1.TEXTURE.MBIN",
						"CUSTOMTEXTURES/CODENAMEAWESOME/BIOMES/DEFROZEN/SMALLPROPS/ICEFORMATION.TEXTURE.MBIN",
						"CUSTOMTEXTURES/CODENAMEAWESOME/BIOMES/DEFROZEN/LARGEPROPS/ROCKTILING.TEXTURE.MBIN",
						"CUSTOMTEXTURES/CODENAMEAWESOME/BIOMES/DEFROZEN/LARGEPROPS/SMOOTHROCKTILING.TEXTURE.MBIN",
					},
					["EXML_CHANGE_TABLE"] = {
						{
							["SPECIAL_KEY_WORDS"] = {"Name","SNOW"},
							["VALUE_CHANGE_TABLE"] = {
								{"Probability",0}
							}
						}
					}
				},
				{--Recolor MARKINGS from texture MBINs that have them
					["MBIN_FILE_SOURCE"] = {
						"CUSTOMTEXTURES/CODENAMEAWESOME/BIOMES/DEFROZEN/LARGEPROPS/SNOWTREEBASE2.TEXTURE.MBIN",
						"CUSTOMTEXTURES/CODENAMEAWESOME/BIOMES/DEFROZEN/MEDIUMPROPS/FROZENLEAF_1.TEXTURE.MBIN"
					},
					["EXML_CHANGE_TABLE"] = {
						{
							["SPECIAL_KEY_WORDS"] = {"Name","MARKINGS"},
							["REPLACE_TYPE"] = "RAW",
							["VALUE_CHANGE_TABLE"] = {
								{[["Palette" value="Snow"]],[["Palette" value="Plant"]]} --Using a raw replace instead of a normal value change because AMUMSS kept targeting the wrong line.
							}
						}
					}
				},
				{--Replace TILINGROCKA.BASE.1.DDS
					["MBIN_FILE_SOURCE"] = {
						"CUSTOMMODELS\CODENAMEAWESOME\BIOMES\DEFROZEN\LARGEPROPS\LARGEROCKS\LARGETILINGROCK_A.MATERIAL.MBIN",
						"CUSTOMMODELS\CODENAMEAWESOME\BIOMES\DEFROZEN\MEDIUMPROPS\MEDIUMROCK\TILINGROCKFROZEN_MAT.MATERIAL.MBIN",
						"CUSTOMMODELS\CODENAMEAWESOME\BIOMES\DEFROZEN\SMALLPROPS\SMALLROCKS\TILINGROCKFROZEN_MAT.MATERIAL.MBIN",
					},
					["EXML_CHANGE_TABLE"] = {
						{
							["REPLACE_TYPE"] = "RAW",
							["VALUE_CHANGE_TABLE"] = {
								{[[TEXTURES/PLANETS/BIOMES/FROZEN/LARGEPROPS/TILINGROCKA.BASE.1.DDS]],[[CUSTOMTEXTURES/CODENAMEAWESOME/BIOMES/DEFROZEN/LARGEPROPS/TILINGROCKA.BASE.1.DDS]]}
							}
						}
					}
				},
				{--Replace SMOOTHROCKTILING
					["MBIN_FILE_SOURCE"] = {
						"CUSTOMMODELS\CODENAMEAWESOME\BIOMES\DEFROZEN\LARGEPROPS\LARGEROCKS\SMOOTHROCKTILING_MAT.MATERIAL.MBIN",
						"CUSTOMMODELS\CODENAMEAWESOME\BIOMES\DEFROZEN\MEDIUMPROPS\MEDIUMROCK\ROCKTEMPLATWE_SMOOTHROCKTILING_MAT.MATERIAL.MBIN",
					},
					["EXML_CHANGE_TABLE"] = {
						{
							["REPLACE_TYPE"] = "RAW",
							["VALUE_CHANGE_TABLE"] = {
								{[[TEXTURES/PLANETS/BIOMES/FROZEN/LARGEPROPS/SMOOTHROCKTILING.DDS]],[[CUSTOMTEXTURES/CODENAMEAWESOME/BIOMES/DEFROZEN/LARGEPROPS/SMOOTHROCKTILING.DDS]]}
							}
						}
					}
				},
				{--Replace SNOWBILLLEAF.BASE.1.DDS
					["MBIN_FILE_SOURCE"] = {
						"CUSTOMMODELS\CODENAMEAWESOME\BIOMES\DEFROZEN\LARGEPROPS\LARGETREE\BILLBOADLEAVES_NEWLEAFMAT.MATERIAL.MBIN",
					},
					["EXML_CHANGE_TABLE"] = {
						{
							["REPLACE_TYPE"] = "RAW",
							["VALUE_CHANGE_TABLE"] = {
								{[[TEXTURES/PLANETS/BIOMES/FROZEN/LARGEPROPS/SNOWBILLLEAF.BASE.1.DDS]],[[CUSTOMTEXTURES/CODENAMEAWESOME/BIOMES/DEFROZEN/LARGEPROPS/SNOWBILLLEAF.BASE.1.DDS]]}
							}
						}
					}
				},
				{--Replace SNOWFROND.BASE.1.DDS
					["MBIN_FILE_SOURCE"] = {
						"CUSTOMMODELS\CODENAMEAWESOME\BIOMES\DEFROZEN\LARGEPROPS\LARGETREE\FROZENFRONDMAT.MATERIAL.MBIN",
					},
					["EXML_CHANGE_TABLE"] = {
						{
							["REPLACE_TYPE"] = "RAW",
							["VALUE_CHANGE_TABLE"] = {
								{[[TEXTURES/PLANETS/BIOMES/FROZEN/LARGEPROPS/SNOWFROND.BASE.1.DDS]],[[CUSTOMTEXTURES/CODENAMEAWESOME/BIOMES/DEFROZEN/LARGEPROPS/SNOWFROND.BASE.1.DDS]]}
							}
						}
					}
				},
				{--Replace SNOWFROND.BASE.2.DDS
					["MBIN_FILE_SOURCE"] = {
						"CUSTOMMODELS\CODENAMEAWESOME\BIOMES\DEFROZEN\MEDIUMPROPS\MEDIUMPLANT\FROND2.MATERIAL.MBIN",
					},
					["EXML_CHANGE_TABLE"] = {
						{
							["REPLACE_TYPE"] = "RAW",
							["VALUE_CHANGE_TABLE"] = {
								{[[TEXTURES/PLANETS/BIOMES/FROZEN/LARGEPROPS/SNOWFROND.BASE.2.DDS]],[[CUSTOMTEXTURES/CODENAMEAWESOME/BIOMES/DEFROZEN/LARGEPROPS/SNOWFROND.BASE.2.DDS]]}
							}
						}
					}
				},
				{--Replace TREEBASE.DDS
					["MBIN_FILE_SOURCE"] = {
						"CUSTOMMODELS\CODENAMEAWESOME\BIOMES\DEFROZEN\LARGEPROPS\LARGEROCKS\FROZENLARGETREE_MAT.MATERIAL.MBIN",
						"CUSTOMMODELS\CODENAMEAWESOME\BIOMES\DEFROZEN\LARGEPROPS\LARGEROCKS\MEDIUMPLANT_FROZENLARGETREE_MAT1.MATERIAL.MBIN",
						"CUSTOMMODELS\CODENAMEAWESOME\BIOMES\DEFROZEN\LARGEPROPS\LARGETREE\FROZENLARGETREE_MAT.MATERIAL.MBIN",
						"CUSTOMMODELS\CODENAMEAWESOME\BIOMES\DEFROZEN\MEDIUMPROPS\MEDIUMPLANT\FROZENLARGETREE_MAT.MATERIAL.MBIN",
						"CUSTOMMODELS\CODENAMEAWESOME\BIOMES\DEFROZEN\MEDIUMPROPS\MEDIUMROCK\FROZENLARGETREE_MAT.MATERIAL.MBIN",
						"CUSTOMMODELS\CODENAMEAWESOME\BIOMES\DEFROZEN\SMALLPROPS\SMALLPLANT\MEDIUMPLANT_FROZENLARGETREE_MAT2.MATERIAL.MBIN",
					},
					["EXML_CHANGE_TABLE"] = {
						{
							["REPLACE_TYPE"] = "RAW",
							["VALUE_CHANGE_TABLE"] = {
								{[[TEXTURES/PLANETS/BIOMES/FROZEN/LARGEPROPS/TREEBASE.DDS]],[[CUSTOMTEXTURES/CODENAMEAWESOME/BIOMES/DEFROZEN/LARGEPROPS/TREEBASE.DDS]]}
							}
						}
					}
				},
				{--Replace TREEBASE.BASE.1.DDS
					["MBIN_FILE_SOURCE"] = {
						"CUSTOMMODELS\CODENAMEAWESOME\BIOMES\DEFROZEN\LARGEPROPS\LARGETREEBARE\FROZENLARGETREE_MAT.MATERIAL.MBIN",
					},
					["EXML_CHANGE_TABLE"] = {
						{
							["REPLACE_TYPE"] = "RAW",
							["VALUE_CHANGE_TABLE"] = {
								{[[TEXTURES/PLANETS/BIOMES/FROZEN/LARGEPROPS/TREEBASE.BASE.1.DDS]],[[CUSTOMTEXTURES/CODENAMEAWESOME/BIOMES/DEFROZEN/LARGEPROPS/TREEBASE.BASE.1.DDS]]}
							}
						}
					}
				},
				{--Replace SNOWTREEBASE2.BASE.1.DDS
					["MBIN_FILE_SOURCE"] = {
						"CUSTOMMODELS\CODENAMEAWESOME\BIOMES\DEFROZEN\MEDIUMPROPS\MEDIUMPLANT\BARK2.MATERIAL.MBIN",
						"CUSTOMMODELS\CODENAMEAWESOME\BIOMES\DEFROZEN\LARGEPROPS\LARGETREE\BARK1.MATERIAL.MBIN",
						"CUSTOMMODELS\CODENAMEAWESOME\BIOMES\DEFROZEN\LARGEPROPS\LARGETREE\BARK.MATERIAL.MBIN",
					},
					["EXML_CHANGE_TABLE"] = {
						{
							["REPLACE_TYPE"] = "RAW",
							["VALUE_CHANGE_TABLE"] = {
								{[[TEXTURES/PLANETS/BIOMES/FROZEN/LARGEPROPS/SNOWTREEBASE2.BASE.1.DDS]],[[CUSTOMTEXTURES/CODENAMEAWESOME/BIOMES/DEFROZEN/LARGEPROPS/SNOWTREEBASE2.BASE.1.DDS]]}
							}
						}
					}
				},
				{--Replace FROZENLEAF_1.BASE.DDS
					["MBIN_FILE_SOURCE"] = {
						"CUSTOMMODELS\CODENAMEAWESOME\BIOMES\DEFROZEN\LARGEPROPS\LARGEROCKS\FROZENLEAF1_MAT.MATERIAL.MBIN",
						"CUSTOMMODELS\CODENAMEAWESOME\BIOMES\DEFROZEN\LARGEPROPS\LARGEROCKS\SMALLPLANT_FROZENLEAF1_MAT.MATERIAL.MBIN",
						"CUSTOMMODELS\CODENAMEAWESOME\BIOMES\DEFROZEN\MEDIUMPROPS\MEDIUMPLANT\FROZENLEAF1_MAT.MATERIAL.MBIN",
						"CUSTOMMODELS\CODENAMEAWESOME\BIOMES\DEFROZEN\MEDIUMPROPS\MEDIUMROCK\FROZENLEAF1_MAT.MATERIAL.MBIN",
						"CUSTOMMODELS\CODENAMEAWESOME\BIOMES\DEFROZEN\MEDIUMPROPS\MEDIUMROCK\LARGEROCKS_FROZENLEAF1_MAT.MATERIAL.MBIN",
						"CUSTOMMODELS\CODENAMEAWESOME\BIOMES\DEFROZEN\SMALLPROPS\SMALLPLANT\FROZENLEAF1_MAT.MATERIAL.MBIN",
					},
					["EXML_CHANGE_TABLE"] = {
						{
							["REPLACE_TYPE"] = "RAW",
							["VALUE_CHANGE_TABLE"] = {
								{[[TEXTURES/PLANETS/BIOMES/FROZEN/MEDIUMPROPS/FROZENLEAF_1.BASE.DDS]],[[CUSTOMTEXTURES/CODENAMEAWESOME/BIOMES/DEFROZEN/MEDIUMPROPS/FROZENLEAF_1.BASE.DDS]]}
							}
						}
					}
				},
				{--Replace MEDIUMROCK_1.DDS
					["MBIN_FILE_SOURCE"] = {
						"CUSTOMMODELS\CODENAMEAWESOME\BIOMES\DEFROZEN\MEDIUMPROPS\MEDIUMROCK\FROZENMEDROCK_MAT.MATERIAL.MBIN",
					},
					["EXML_CHANGE_TABLE"] = {
						{
							["REPLACE_TYPE"] = "RAW",
							["VALUE_CHANGE_TABLE"] = {
								{[[TEXTURES/PLANETS/BIOMES/FROZEN/MEDIUMPROPS/MEDIUMROCK_1.DDS]],[[CUSTOMTEXTURES/CODENAMEAWESOME/BIOMES/DEFROZEN/MEDIUMPROPS/MEDIUMROCK_1.DDS]]}
							}
						}
					}
				},
				{--Replace ROCKTILING.DDS
					["MBIN_FILE_SOURCE"] = {
						"CUSTOMMODELS\CODENAMEAWESOME\BIOMES\DEFROZEN\SMALLPROPS\SMALLROCKSSHARDS\SMALLROCKBASE_MAT.MATERIAL.MBIN",
					},
					["EXML_CHANGE_TABLE"] = {
						{
							["REPLACE_TYPE"] = "RAW",
							["VALUE_CHANGE_TABLE"] = {
								{[[TEXTURES/PLANETS/BIOMES/FROZEN/LARGEPROPS/ROCKTILING.DDS]],[[CUSTOMTEXTURES/CODENAMEAWESOME/BIOMES/DEFROZEN/LARGEPROPS/ROCKTILING.DDS]]}
							}
						}
					}
				},
				{--Replace BARKSNOWDECAL.BASE.DDS with BARKGROUNDDECAL.BASE.1
					["MBIN_FILE_SOURCE"] = {
						"CUSTOMMODELS\CODENAMEAWESOME\BIOMES\DEFROZEN\LARGEPROPS\LARGETREE\BARK.MATERIAL.MBIN",
						"CUSTOMMODELS\CODENAMEAWESOME\BIOMES\DEFROZEN\LARGEPROPS\LARGETREE\BARK1.MATERIAL.MBIN",
					},
					["EXML_CHANGE_TABLE"] = {
						{
							["REPLACE_TYPE"] = "RAW",
							["VALUE_CHANGE_TABLE"] = {
								{[[TEXTURES/PLANETS/BIOMES/FROZEN/LARGEPROPS/BARKSNOWDECAL.BASE.DDS]],[[TEXTURES/PLANETS/BIOMES/COMMON/BARK/BARKGROUNDDECAL.BASE.1.DDS]]}
							}
						}
					}
				},
				{--Replace ICETILING with ROCKTILING
					["MBIN_FILE_SOURCE"] = {
						"CUSTOMMODELS\CODENAMEAWESOME\BIOMES\DEFROZEN\SMALLPROPS\SMALLROCKS\ICE_MAT.MATERIAL.MBIN",
						"CUSTOMMODELS\CODENAMEAWESOME\BIOMES\DEFROZEN\MEDIUMPROPS\MEDIUMICEDRIFTS\ICE_MAT.MATERIAL.MBIN",
						"CUSTOMMODELS\CODENAMEAWESOME\BIOMES\DEFROZEN\LARGEPROPS\LARGEROCKS\ICE_MAT.MATERIAL.MBIN",
					},
					["EXML_CHANGE_TABLE"] = {
						{
							["REPLACE_TYPE"] = "RAW",
							["VALUE_CHANGE_TABLE"] = {
								{[[TEXTURES/PLANETS/BIOMES/FROZEN/LARGEPROPS/ICETILING.]],[[CUSTOMTEXTURES/CODENAMEAWESOME/BIOMES/DEFROZEN/LARGEPROPS/ROCKTILING.]]}
							}
						}
					}
				},
				{--Replace SNOWTILING with ROCKTILING
					["MBIN_FILE_SOURCE"] = {
						"CUSTOMMODELS\CODENAMEAWESOME\BIOMES\DEFROZEN\SMALLPROPS\SMALLROCKSSHARDS\SNOWTILING_MAT.MATERIAL.MBIN",
						"CUSTOMMODELS\CODENAMEAWESOME\BIOMES\DEFROZEN\SMALLPROPS\SMALLROCKSSHARDS\SMALLROCKS_SNOWTILING_MAT.MATERIAL.MBIN",
						"CUSTOMMODELS\CODENAMEAWESOME\BIOMES\DEFROZEN\SMALLPROPS\SMALLROCKS\SNOWTILING_MAT.MATERIAL.MBIN",
						"CUSTOMMODELS\CODENAMEAWESOME\BIOMES\DEFROZEN\MEDIUMPROPS\MEDIUMROCK\FLATROCKS_SNOWTILING_MAT.MATERIAL.MBIN",
						"CUSTOMMODELS\CODENAMEAWESOME\BIOMES\DEFROZEN\MEDIUMPROPS\MEDIUMICEDRIFTS\SNOWTILING_MAT.MATERIAL.MBIN",
						"CUSTOMMODELS\CODENAMEAWESOME\BIOMES\DEFROZEN\LARGEPROPS\LARGETREEBARE\SNOWTILING_MAT.MATERIAL.MBIN",
						"CUSTOMMODELS\CODENAMEAWESOME\BIOMES\DEFROZEN\LARGEPROPS\LARGETREE\SNOWTILING_MAT.MATERIAL.MBIN",
					},
					["EXML_CHANGE_TABLE"] = {
						{
							["REPLACE_TYPE"] = "RAW",
							["VALUE_CHANGE_TABLE"] = {
								{[[TEXTURES/PLANETS/BIOMES/FROZEN/LARGEPROPS/SNOWTILING.]],[[CUSTOMTEXTURES/CODENAMEAWESOME/BIOMES/DEFROZEN/LARGEPROPS/ROCKTILING.]]}
							}
						}
					}
				},
				{--Remove snow meshes from LARGETREE
					["MBIN_FILE_SOURCE"] = {"CUSTOMMODELS\CODENAMEAWESOME\BIOMES\DEFROZEN\LARGEPROPS\LARGETREE.SCENE.MBIN"},
					["EXML_CHANGE_TABLE"] = {
						{
							["SPECIAL_KEY_WORDS"] = {"Value","CUSTOMMODELS\CODENAMEAWESOME\BIOMES\DEFROZEN\LARGEPROPS\LARGETREE\SNOWTILING_MAT.MATERIAL.MBIN"},
							["SECTION_UP"] = 2,
							["REMOVE"] = "SECTION",
							["REPLACE_TYPE"] = "ALL",
						}
					}
				},
				{--Remove snow and icicle meshes from LARGETREEBARE
					["MBIN_FILE_SOURCE"] = {"CUSTOMMODELS\CODENAMEAWESOME\BIOMES\DEFROZEN\LARGEPROPS\LARGETREEBARE.SCENE.MBIN"},
					["EXML_CHANGE_TABLE"] = {
						{
							["SPECIAL_KEY_WORDS"] = {"Value","CUSTOMMODELS\CODENAMEAWESOME\BIOMES\DEFROZEN\LARGEPROPS\LARGETREEBARE\SNOWTILING_MAT.MATERIAL.MBIN"},
							["SECTION_UP"] = 2,
							["REMOVE"] = "SECTION",
							["REPLACE_TYPE"] = "ALL",
						},
						{
							["SPECIAL_KEY_WORDS"] = {"Value","CUSTOMMODELS\CODENAMEAWESOME\BIOMES\DEFROZEN\LARGEPROPS\LARGETREEBARE\HANGINGICESOLID_MAT.MATERIAL.MBIN"},
							["SECTION_UP"] = 2,
							["REMOVE"] = "SECTION",
							["REPLACE_TYPE"] = "ALL",
						}
					}
				},
			}
		}
	}
}
--NOTE: ANYTHING NOT in table NMS_MOD_DEFINITION_CONTAINER IS IGNORED AFTER THE SCRIPT IS LOADED
--IT IS BETTER TO ADD THINGS AT THE TOP IF YOU NEED TO
--DON'T ADD ANYTHING PASS THIS POINT HERE