NMS_MOD_DEFINITION_CONTAINER = 
{
  ["MOD_BATCHNAME"] 			= "zzCodenameAwesome-Assets.pak",     --the name of the pak created (if not combined) - REQUIRED
  ["MOD_FILENAME"] 			= "zzCodenameAwesome-Assets-SnowyHUGESPIKEROCK.pak",     --the name of the pak created (if not combined) - REQUIRED
  ["MOD_DESCRIPTION"]		= "The props from the HugeRocks biome with their texture swapped out for an icy one.",         --optional, for reference
  ["MOD_AUTHOR"]				= "",         --optional, for reference
  ["NMS_VERSION"]				= "2.0",     --optional, for reference
  ["MODIFICATIONS"] 		=             --REQUIRED SECTION
	{
		{
			["MBIN_CHANGE_TABLE"] =  {
				{--Create the model
					["MBIN_FILE_SOURCE"] = {
						{"MODELS/PLANETS/BIOMES/HUGEPROPS/HUGEROCK/HUGESPIKEROCK.DESCRIPTOR.MBIN","CUSTOMMODELS/CODENAMEAWESOME/BIOMES/HUGEPROPS/SNOWYHUGEROCK/HUGESPIKEROCK.DESCRIPTOR.MBIN"},
						{"MODELS/PLANETS/BIOMES/HUGEPROPS/HUGEROCK/HUGESPIKEROCK.SCENE.MBIN","CUSTOMMODELS/CODENAMEAWESOME/BIOMES/HUGEPROPS/SNOWYHUGEROCK/HUGESPIKEROCK.SCENE.MBIN"},
					}
				},
				{--Change the filepaths in the scene.
					["MBIN_FILE_SOURCE"] = {"CUSTOMMODELS/CODENAMEAWESOME/BIOMES/HUGEPROPS/SNOWYHUGEROCK/HUGESPIKEROCK.SCENE.MBIN"},
					["EXML_CHANGE_TABLE"] = {
						{
							["SPECIAL_KEY_WORDS"] = {"Name","MATERIAL"},
							["REPLACE_TYPE"] = "RAW",
							["VALUE_CHANGE_TABLE"] = {
								{[[MODELS\PLANETS\BIOMES\HUGEPROPS\HUGEROCK\HUGESPIKEROCK\LARGESPIKEROCK_MAT.MATERIAL.MBIN]],[[MODELS\PLANETS\BIOMES\FROZEN\MEDIUMPROPS\MEDIUMICEDRIFTS\ICE_MAT.MATERIAL.MBIN]]}
							}
						}
					}
				},
			},
		},
	}
}
--NOTE: ANYTHING NOT in table NMS_MOD_DEFINITION_CONTAINER IS IGNORED AFTER THE SCRIPT IS LOADED
--IT IS BETTER TO ADD THINGS AT THE TOP IF YOU NEED TO
--DON'T ADD ANYTHING PASS THIS POINT HERE