--DO NOT USE "REMOVE" TAGS WHEN COPYING FILES
--This script is intended for use with OpenBiomeExtender and will not work without it.
--Place the OpenBiomeExtender.pak into your ModScript folder when you run this script

DENSITY_MULTIPLIER = 0.25

NMS_MOD_DEFINITION_CONTAINER = 
{
  ["MOD_BATCHNAME"] 			= "zzOpenBiomeExtender-MergedModules.pak",
  --["MOD_FILENAME"] 			= "zzCodenameAwesome-OpenBE-SwampMushroomsInOtherBiomes.pak",
  ["MOD_DESCRIPTION"]		= "Adds a chance for Swamp mushrooms in other biomes",
  ["MOD_AUTHOR"]				= "CodenameAwesome",
  ["NMS_VERSION"]				= "3.13",
  ["MODIFICATIONS"] 		= 
	{
		{
			["MBIN_CHANGE_TABLE"] = 
			{ 
				{
					["MBIN_FILE_SOURCE"] 	= {
					"OPENBE/BIOMEFILES/BARREN/BARRENINFESTEDBIOME.MBIN",
					--To Do: Make a snowy variant of this object list for the frozen biome
					--"OPENBE/BIOMEFILES/FROZEN/FROZENBIOME.MBIN",
					--"OPENBE/BIOMEFILES/FROZEN/FROZENINFESTEDBIOME.MBIN",
					"OPENBE/BIOMEFILES/HUGEPROPS/HUGELUSH/HUGELUSHBIOME.MBIN",
					"OPENBE/BIOMEFILES/HUGEPROPS/HUGERING/HUGERINGBIOME.MBIN",
					"OPENBE/BIOMEFILES/HUGEPROPS/HUGETOXIC/HUGETOXICBIOME.MBIN",
					"OPENBE/BIOMEFILES/LUSH/LUSHBIOME.MBIN",
					"OPENBE/BIOMEFILES/LUSH/LUSHBUBBLESBIOME.MBIN",
					"OPENBE/BIOMEFILES/LUSH/LUSHINFESTEDBIOME.MBIN",
					"OPENBE/BIOMEFILES/LUSH/LUSHROOMABIOME.MBIN",
					"OPENBE/BIOMEFILES/LUSH/LUSHROOMBBIOME.MBIN",
					"OPENBE/BIOMEFILES/RADIOACTIVE/RADIOACTIVEBIOME.MBIN",
					"OPENBE/BIOMEFILES/RADIOACTIVE/RADIOINFESTEDBIOME.MBIN",
					"OPENBE/BIOMEFILES/SCORCHED/SCORCHINFESTEDBIOME.MBIN",
					"OPENBE/BIOMEFILES/TOXIC/TOXICBIOME.MBIN",
					"OPENBE/BIOMEFILES/TOXIC/TOXICEGGSBIOME.MBIN",
					"OPENBE/BIOMEFILES/TOXIC/TOXICINFESTEDBIOME.MBIN",
					"OPENBE/BIOMEFILES/TOXIC/TOXICSPORESBIOME.MBIN",
					"OPENBE/BIOMEFILES/TOXIC/TOXICTENTACLESBIOME.MBIN",
					"OPENBE/BIOMEFILES/WEIRD/HYDROGARDEN/HYDROGARDENBIOME.MBIN",
					},
					["EXML_CHANGE_TABLE"] = {
						--For testing purposes uncomment the following line to remove all other object lists
						--{["SPECIAL_KEY_WORDS"] = {"Name","OBJECTS","Value","IGNORE"},["REMOVE"] = "SECTION",},
						{
							["SPECIAL_KEY_WORDS"] = {"Name","OBJECTS"},
							["PRECEDING_KEY_WORDS"] = {"Options"},
							["ADD"] =
[[        <Property value="NMSString0x80.xml">
          <Property name="Value" value="OPENBE/OBJECTFILES/VANILLA/OBJECTS/SWAMP/SWAMPOBJECTSFULL.MBIN" />
        </Property>]]
						},
					}
				},
				{
					["MBIN_FILE_SOURCE"] 	= {
					"OPENBE/BIOMEFILES/BARREN/BARRENINFESTEDBIOME.MBIN",
					--To Do: Make a snowy variant of this object list for the frozen biome
					--"OPENBE/BIOMEFILES/FROZEN/FROZENBIOME.MBIN",
					--"OPENBE/BIOMEFILES/FROZEN/FROZENINFESTEDBIOME.MBIN",
					"OPENBE/BIOMEFILES/HUGEPROPS/HUGERING/HUGERINGBIOME.MBIN",
					"OPENBE/BIOMEFILES/HUGEPROPS/HUGETOXIC/HUGETOXICBIOME.MBIN",
					"OPENBE/BIOMEFILES/RADIOACTIVE/RADIOACTIVEBIOME.MBIN",
					"OPENBE/BIOMEFILES/RADIOACTIVE/RADIOINFESTEDBIOME.MBIN",
					"OPENBE/BIOMEFILES/SCORCHED/SCORCHINFESTEDBIOME.MBIN",
					"OPENBE/BIOMEFILES/TOXIC/TOXICBIOME.MBIN",
					"OPENBE/BIOMEFILES/TOXIC/TOXICEGGSBIOME.MBIN",
					"OPENBE/BIOMEFILES/TOXIC/TOXICINFESTEDBIOME.MBIN",
					"OPENBE/BIOMEFILES/TOXIC/TOXICSPORESBIOME.MBIN",
					"OPENBE/BIOMEFILES/TOXIC/TOXICTENTACLESBIOME.MBIN",
					"OPENBE/BIOMEFILES/WEIRD/HYDROGARDEN/HYDROGARDENBIOME.MBIN",
					},
					["EXML_CHANGE_TABLE"] = {
						{
							["SPECIAL_KEY_WORDS"] = {"Name","DETAILOBJECTS"},
							["PRECEDING_KEY_WORDS"] = {"Options"},
							["ADD"] =
[[        <Property value="NMSString0x80.xml">
          <Property name="Value" value="OPENBE/OBJECTFILES/VANILLA/DETAILOBJECTS/SWAMP/SWAMPOBJECTSFULL.MBIN" />
        </Property>]]
						},
					}
				},
			}
		},
	}
}
--NOTE: ANYTHING NOT in table NMS_MOD_DEFINITION_CONTAINER IS IGNORED AFTER THE SCRIPT IS LOADED
--IT IS BETTER TO ADD THINGS AT THE TOP IF YOU NEED TO
--DON'T ADD ANYTHING PASS THIS POINT HERE